package dm

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"unicode"
)

type OfflineDataFile struct {
	GroupID    uint32
	FileID     int16
	Tablespace string
	Path       string
}

// SizedReaderAt is a random-access logical file whose size is known without
// relying on os.Stat. Raw DMASM files implement this interface.
type SizedReaderAt interface {
	io.ReaderAt
	Size() int64
}

// OfflineDataSource binds a logical reader to the database group/file identity
// used by page plans and storage roots.
type OfflineDataSource struct {
	GroupID    uint32
	FileID     int16
	Tablespace string
	Path       string
	Reader     SizedReaderAt
}

func ScanOfflineDataFiles(controlPath string, controlDULPath string, dataDir string) ([]OfflineDataFile, error) {
	refs, err := resolveDataFiles(controlPath, controlDULPath, dataDir)
	if err != nil {
		return nil, err
	}
	seen := make(map[dataFileKey]bool)
	files := make([]OfflineDataFile, 0, len(refs))
	for _, ref := range refs {
		files = append(files, OfflineDataFile{
			GroupID:    ref.key.groupID,
			FileID:     ref.key.fileID,
			Tablespace: ref.tablespaceName,
			Path:       ref.path,
		})
		seen[ref.key] = true
	}
	tablespaceNames := loadTablespaceNames(controlPath, controlDULPath)
	files = append(files, scanAllDBFFilesByPageHeader(dataDir, tablespaceNames, seen)...)
	sort.Slice(files, func(i, j int) bool {
		if files[i].GroupID == files[j].GroupID {
			return files[i].FileID < files[j].FileID
		}
		return files[i].GroupID < files[j].GroupID
	})
	return files, nil
}

func WriteControlDUL(path string, files []OfflineDataFile) error {
	if strings.TrimSpace(path) == "" {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return err
	}
	var out strings.Builder
	out.WriteString("# Generated by dmdul bootstrap. Review paths before reuse.\n")
	out.WriteString("# format: datafile <tablespace_id> <file_id> <tablespace_name> <path>\n")
	for _, file := range files {
		if strings.TrimSpace(file.Path) == "" {
			continue
		}
		dataPath := file.Path
		if !IsASMPath(dataPath) {
			if abs, err := filepath.Abs(dataPath); err == nil {
				dataPath = abs
			}
		}
		tablespace := file.Tablespace
		if tablespace == "" {
			tablespace = inferTablespaceNameFromDataFile(dataPath, file.GroupID)
		}
		out.WriteString(fmt.Sprintf("datafile %d %d %s %s\n", file.GroupID, file.FileID, tablespace, quoteControlDULValue(dataPath)))
	}
	return os.WriteFile(path, []byte(out.String()), 0644)
}

func scanAllDBFFilesByPageHeader(dataDir string, tablespaceNames map[uint32]string, seen map[dataFileKey]bool) []OfflineDataFile {
	if strings.TrimSpace(dataDir) == "" {
		return nil
	}
	entries, err := os.ReadDir(dataDir)
	if err != nil {
		return nil
	}
	var files []OfflineDataFile
	for _, entry := range entries {
		if entry.IsDir() || !strings.EqualFold(filepath.Ext(entry.Name()), ".DBF") {
			continue
		}
		path := filepath.Join(dataDir, entry.Name())
		key, ok := dataFileKeyForControlDUL(path)
		if !ok || seen[key] {
			continue
		}
		tablespace := tablespaceNames[key.groupID]
		if tablespace == "" {
			tablespace = inferTablespaceNameFromDataFile(path, key.groupID)
		}
		files = append(files, OfflineDataFile{
			GroupID:    key.groupID,
			FileID:     key.fileID,
			Tablespace: tablespace,
			Path:       path,
		})
		seen[key] = true
	}
	return files
}

func dataFileKeyForControlDUL(path string) (dataFileKey, bool) {
	key, ok := dataFileKeyFromPageHeader(path)
	if !ok {
		return dataFileKey{}, false
	}
	base := strings.ToUpper(strings.TrimSuffix(filepath.Base(path), filepath.Ext(path)))
	switch base {
	case "SYSTEM":
		key.groupID, key.fileID = 0, 0
	case "ROLL":
		key.groupID, key.fileID = 1, 0
	case "TEMP":
		key.groupID, key.fileID = 3, 0
	case "MAIN":
		key.groupID, key.fileID = 4, 0
	}
	return key, true
}

func readControlDUL(path string) ([]OfflineDataFile, bool) {
	if strings.TrimSpace(path) == "" {
		return nil, false
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, false
	}
	defer file.Close()

	var files []OfflineDataFile
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "--") {
			continue
		}
		fields := splitControlDULFields(line)
		if len(fields) < 4 || !strings.EqualFold(fields[0], "datafile") {
			continue
		}
		groupID, err := strconv.ParseUint(fields[1], 10, 32)
		if err != nil {
			continue
		}
		fileID, err := strconv.ParseInt(fields[2], 10, 16)
		if err != nil {
			continue
		}
		entry := OfflineDataFile{GroupID: uint32(groupID), FileID: int16(fileID)}
		if len(fields) == 4 {
			entry.Path = fields[3]
			entry.Tablespace = inferTablespaceNameFromDataFile(entry.Path, entry.GroupID)
		} else {
			entry.Tablespace = fields[3]
			entry.Path = strings.Join(fields[4:], " ")
		}
		files = append(files, entry)
	}
	if len(files) == 0 {
		return nil, false
	}
	return files, true
}

func mergeControlDULTablespaceNames(names map[uint32]string, controlDULPath string) {
	files, ok := readControlDUL(controlDULPath)
	if !ok {
		return
	}
	for _, file := range files {
		if file.Tablespace != "" {
			names[file.GroupID] = file.Tablespace
		}
	}
}

func inferTablespaceNameFromDataFile(path string, groupID uint32) string {
	if name := defaultTablespaceNames()[groupID]; name != "" {
		return name
	}
	// Control files may originate on a different OS from the recovery host.
	portablePath := strings.ReplaceAll(path, "\\", "/")
	base := strings.TrimSuffix(filepath.Base(portablePath), filepath.Ext(portablePath))
	base = strings.ToUpper(strings.TrimSpace(base))
	if base == "" {
		return ""
	}
	digitCount := 0
	for i := len(base) - 1; i >= 0; i-- {
		if base[i] < '0' || base[i] > '9' {
			break
		}
		digitCount++
	}
	if digitCount >= 2 && len(base) > digitCount {
		base = strings.TrimRight(base[:len(base)-digitCount], "_-")
	}
	return base
}

func quoteControlDULValue(value string) string {
	if value == "" {
		return `""`
	}
	if strings.ContainsFunc(value, unicode.IsSpace) || strings.Contains(value, `"`) {
		return `"` + strings.ReplaceAll(value, `"`, `""`) + `"`
	}
	return value
}

func splitControlDULFields(line string) []string {
	var fields []string
	var current strings.Builder
	inQuote := false
	for i := 0; i < len(line); i++ {
		ch := rune(line[i])
		if ch == '"' {
			if inQuote && i+1 < len(line) && line[i+1] == '"' {
				current.WriteByte('"')
				i++
				continue
			}
			inQuote = !inQuote
			continue
		}
		if unicode.IsSpace(ch) && !inQuote {
			if current.Len() > 0 {
				fields = append(fields, current.String())
				current.Reset()
			}
			continue
		}
		current.WriteRune(ch)
	}
	if current.Len() > 0 {
		fields = append(fields, current.String())
	}
	return fields
}
