package dm

import (
	"bytes"
	"encoding/binary"
	"encoding/hex"
	"fmt"
	"io"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDataFilePageReaderUsesLogicalReader(t *testing.T) {
	const pageSize = 8192
	raw := make([]byte, pageSize*2)
	copy(raw[pageSize+0x100:], "DMASM-LOGICAL-PAGE")
	source := fixedSizeReaderAt{ReaderAt: bytes.NewReader(raw), size: int64(len(raw))}
	key := dataFileKey{groupID: 5, fileID: 0}
	reader := newDataFilePageReader([]dataFileRef{{
		key: key, path: "+DMDATA/DMDB/TBS01.DBF", reader: source,
	}}, pageSize)
	defer reader.close()
	page, err := reader.readPage(dataPageRef{key: key, pageNo: 1})
	if err != nil {
		t.Fatal(err)
	}
	if got := string(page[0x100 : 0x100+len("DMASM-LOGICAL-PAGE")]); got != "DMASM-LOGICAL-PAGE" {
		t.Fatalf("logical page payload = %q", got)
	}
}

func TestSplitDataOutputRouterLimitsOpenFilesAndReopensForAppend(t *testing.T) {
	dir := t.TempDir()
	tables := make(map[uint32]dataTableInfo)
	for i := uint32(1); i <= maxOpenSplitDataFiles+8; i++ {
		tables[i] = dataTableInfo{table: dictionaryObject{ID: i, Owner: "APP", Name: fmt.Sprintf("T_%02d", i)}}
	}
	router, err := newDataOutputRouter(DataExportOptions{
		TableOutputPath: func(_ string, table string, _ uint32) string {
			return filepath.Join(dir, table+"_data.sql")
		},
	}, "sql", tables)
	if err != nil {
		t.Fatalf("newDataOutputRouter failed: %v", err)
	}
	for i := uint32(1); i <= maxOpenSplitDataFiles+8; i++ {
		if err := router.writeRow(tables[i], fmt.Sprintf("ROW_%02d", i), nil); err != nil {
			t.Fatalf("writeRow(%d) failed: %v", i, err)
		}
		if len(router.filesByTable) > maxOpenSplitDataFiles {
			t.Fatalf("open files = %d, limit = %d", len(router.filesByTable), maxOpenSplitDataFiles)
		}
	}
	if err := router.writeRow(tables[1], "ROW_01_AGAIN", nil); err != nil {
		t.Fatalf("reopened writeRow failed: %v", err)
	}
	if err := router.close(); err != nil {
		t.Fatalf("router.close failed: %v", err)
	}
	raw, err := os.ReadFile(filepath.Join(dir, "T_01_data.sql"))
	if err != nil {
		t.Fatalf("ReadFile failed: %v", err)
	}
	text := string(raw)
	if strings.Count(text, "Generated by dmdul export-data") != 1 {
		t.Fatalf("SQL header should be written once, got %q", text)
	}
	for _, want := range []string{"ROW_01", "ROW_01_AGAIN"} {
		if !strings.Contains(text, want) {
			t.Fatalf("split SQL should contain %q, got %q", want, text)
		}
	}
}

func TestSplitDMPOutputRouterLimitsOpenFilesAndFinalizesEveryTable(t *testing.T) {
	dir := t.TempDir()
	tables := make(map[uint32]dataTableInfo)
	for i := uint32(1); i <= maxOpenSplitDataFiles+8; i++ {
		tables[i] = dataTableInfo{
			table:   dictionaryObject{ID: i, Owner: "APP", Name: fmt.Sprintf("T_%02d", i)},
			columns: []columnDef{{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"}},
		}
	}
	charset, err := dmpCharsetForDataExport("utf-8")
	if err != nil {
		t.Fatal(err)
	}
	router, err := newDataOutputRouter(DataExportOptions{
		TableOutputPath: func(_ string, table string, _ uint32) string {
			return filepath.Join(dir, table+"_data.dmp")
		},
	}, "dmp", tables, dataDMPOutputConfig{charset: charset, extentSize: 16, pageSize: 8192})
	if err != nil {
		t.Fatalf("newDataOutputRouter failed: %v", err)
	}
	for i := uint32(1); i <= maxOpenSplitDataFiles+8; i++ {
		if err := router.writeRow(tables[i], "", nil, []DMPField{DMPShortField([]byte(fmt.Sprintf("%d", i)))}); err != nil {
			t.Fatalf("writeRow(%d) failed: %v", i, err)
		}
		if len(router.filesByTable) > maxOpenSplitDataFiles {
			t.Fatalf("open DMP files = %d, limit = %d", len(router.filesByTable), maxOpenSplitDataFiles)
		}
	}
	if err := router.writeRow(tables[1], "", nil, []DMPField{DMPShortField([]byte("101"))}); err != nil {
		t.Fatalf("reopened DMP write failed: %v", err)
	}
	if err := router.close(); err != nil {
		t.Fatalf("router.close failed: %v", err)
	}
	for _, id := range []uint32{1, maxOpenSplitDataFiles + 8} {
		info, err := InspectDMP(filepath.Join(dir, fmt.Sprintf("T_%02d_data.dmp", id)))
		if err != nil {
			t.Fatalf("InspectDMP(%d) failed: %v", id, err)
		}
		wantRows := uint64(1)
		if id == 1 {
			wantRows = 2
		}
		if len(info.Tables) != 1 || info.Tables[0].RowCount != wantRows {
			t.Fatalf("table %d dmp rows=%+v want=%d", id, info.Tables, wantRows)
		}
	}
}

func TestLocateRowsInDataPage(t *testing.T) {
	page := make([]byte, 8192)
	binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)
	pos := dataRowAreaStart
	putTestRow(page, pos, 5, 0x00)
	pos += 5
	putTestRow(page, pos, 4, 0x01)
	page[pos] = 0xFF
	page[pos+1] = 0xFF
	pos += 4
	putTestRow(page, pos, 6, 0x00)
	pos += 6
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 3)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], uint16(pos))
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 2)
	putTestDataPageSlot(page, 8192, 3, 1, dataRowAreaStart)
	putTestDataPageSlot(page, 8192, 3, 2, dataRowAreaStart+5)
	putTestDataPageSlot(page, 8192, 3, 3, dataRowAreaStart+9)

	if !isProbableDMDataPage(page, 8192) {
		t.Fatal("expected test page to look like a DM data page")
	}
	binary.LittleEndian.PutUint16(page[dataPageTreeLevelOff:], 1)
	if isProbableDMDataPage(page, 8192) {
		t.Fatal("expected non-leaf tree page to be skipped")
	}
	binary.LittleEndian.PutUint16(page[dataPageTreeLevelOff:], 0)
	rows := locateRowsInDataPage(page, 8192, 2)
	if len(rows) != 2 {
		t.Fatalf("expected 2 live rows, got %d", len(rows))
	}
	if rows[0].slotNo != 1 || rows[0].offset != dataRowAreaStart || rows[0].length != 5 {
		t.Fatalf("unexpected first row: %+v", rows[0])
	}
	if rows[1].slotNo != 3 || rows[1].offset != dataRowAreaStart+9 || rows[1].length != 6 {
		t.Fatalf("unexpected second row: %+v", rows[1])
	}
}

func TestLocateRowsInHeapDataPageUsesSlotArray(t *testing.T) {
	page := make([]byte, 8192)
	binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)
	offsets := []int{0x4FA, 0x3D4, 0x2AE, 0x188, 0x62}
	for i, off := range offsets {
		putTestRow(page, off, 0x126, 0x00)
		page[off+3] = byte(i + 1)
	}
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 7)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], 0x620)
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 5)
	putTestDataPageSlot(page, 8192, 7, 1, 0x5A)
	for i, off := range offsets {
		putTestDataPageSlot(page, 8192, 7, i+2, off)
	}
	putTestDataPageSlot(page, 8192, 7, 7, 0x52)

	rows := locateRowsInDataPage(page, 8192, 5)
	if len(rows) != 5 {
		t.Fatalf("expected 5 live rows, got %d", len(rows))
	}
	if rows[0].offset != 0x62 || rows[4].offset != 0x4FA {
		t.Fatalf("rows were not sorted by physical offset: %+v", rows)
	}
	if rows[0].length != 0x126 {
		t.Fatalf("heap row length = %d, want 0x126", rows[0].length)
	}
}

func TestLocateRowsTreats002CAnd002EAsPhysicalLengths(t *testing.T) {
	for _, rowLength := range []int{0x2C, 0x2E} {
		t.Run(fmt.Sprintf("length_%02X", rowLength), func(t *testing.T) {
			const pageSize = 8192
			page := make([]byte, pageSize)
			binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)
			putTestRow(page, dataRowAreaStart, rowLength, 0x00)
			binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 3)
			binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], uint16(dataRowAreaStart+rowLength))
			binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
			putTestDataPageSlot(page, pageSize, 3, 1, 0xFFFF)
			putTestDataPageSlot(page, pageSize, 3, 2, dataRowAreaStart)
			putTestDataPageSlot(page, pageSize, 3, 3, 0xFFFF)

			rows := locateRowsInDataPage(page, pageSize, 1)
			if len(rows) != 1 || rows[0].offset != dataRowAreaStart || int(rows[0].length) != rowLength {
				t.Fatalf("row header 00 %02X was not decoded as length %d: %+v", rowLength, rowLength, rows)
			}
		})
	}
}

func TestLocateRowsUsesConfiguredDMPageSize(t *testing.T) {
	for _, pageSize := range []int{4096, 8192, 16384, 32768} {
		t.Run(fmt.Sprintf("page_%d", pageSize), func(t *testing.T) {
			page := make([]byte, pageSize)
			binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)
			putTestRow(page, dataRowAreaStart, 7, 0x00)
			binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 1)
			binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], dataRowAreaStart+7)
			binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
			putTestDataPageSlot(page, pageSize, 1, 1, dataRowAreaStart)

			rows := locateRowsInDataPage(page, uint32(pageSize), 1)
			if len(rows) != 1 || rows[0].offset != dataRowAreaStart || rows[0].length != 7 {
				t.Fatalf("page size %d row location failed: %+v", pageSize, rows)
			}
		})
	}
}

func TestLocateRowsNormalIsSlotOnlyAndRecoveryIncludesPhysicalRows(t *testing.T) {
	const pageSize = 8192
	page := make([]byte, pageSize)
	binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)

	liveOff := dataRowAreaStart
	deletedOff := liveOff + 5
	holeOff := deletedOff + 5
	putTestRow(page, liveOff, 5, 0x00)
	putTestRow(page, deletedOff, 5, 0x00)
	binary.BigEndian.PutUint16(page[deletedOff:], dataRowDeletedMask|5)
	putTestRow(page, holeOff, 5, 0x00)
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 3)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], uint16(holeOff+5))
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
	putTestDataPageSlot(page, pageSize, 3, 1, liveOff)
	putTestDataPageSlot(page, pageSize, 3, 2, deletedOff)
	putTestDataPageSlot(page, pageSize, 3, 3, 0x52)

	normal := locateRowsInDataPage(page, pageSize, 1)
	if len(normal) != 1 || normal[0].offset != uint16(liveOff) || normal[0].deleted || !normal[0].fromSlot {
		t.Fatalf("normal unload did not stay on the live slot: %+v", normal)
	}

	recovery := locateRowsInDataPageForRecovery(page, pageSize)
	if len(recovery) != 3 {
		t.Fatalf("recovery rows=%+v, want live slot, deleted slot, and physical hole", recovery)
	}
	if !recovery[1].deleted || !recovery[1].fromSlot || recovery[1].offset != uint16(deletedOff) {
		t.Fatalf("deleted slot was not preserved for recovery: %+v", recovery[1])
	}
	if recovery[2].fromSlot || recovery[2].offset != uint16(holeOff) {
		t.Fatalf("physical hole was not recovery-only: %+v", recovery[2])
	}
}

func TestLocateRowsDoesNotTrustStaleRecordCount(t *testing.T) {
	const pageSize = 8192
	page := make([]byte, pageSize)
	binary.LittleEndian.PutUint32(page[dmPageKindOff:], dmPageKindRowData)
	firstOff := dataRowAreaStart
	secondOff := firstOff + 5
	putTestRow(page, firstOff, 5, 0x00)
	putTestRow(page, secondOff, 5, 0x00)
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 2)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], uint16(secondOff+5))
	// DELETE/space-reuse experiments show that n_rec can lag the slot state.
	// It is a page hint, not a safe upper bound for active slot rows.
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
	putTestDataPageSlot(page, pageSize, 2, 1, firstOff)
	putTestDataPageSlot(page, pageSize, 2, 2, secondOff)

	rows := locateRowsInDataPage(page, pageSize, 1)
	if len(rows) != 2 || rows[0].offset != uint16(firstOff) || rows[1].offset != uint16(secondOff) {
		t.Fatalf("stale n_rec truncated active slot rows: %+v", rows)
	}
}

func TestDecodeDeletedDataRowHeader(t *testing.T) {
	page := make([]byte, 8192)
	binary.BigEndian.PutUint16(page[dataRowAreaStart:], dataRowDeletedMask|0x69)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], dataRowAreaStart+0x69)
	header, ok := decodeDataRowHeader(page, dataRowAreaStart, 8192, dataRowAreaStart+0x69)
	if !ok || header.length != 0x69 || !header.deleted {
		t.Fatalf("deleted row header decoded as %+v, ok=%t", header, ok)
	}
}

func TestDecodeDataRowControlTail(t *testing.T) {
	// Captured from an uncommitted DELETE whose V$TRX.ID was 135899. The
	// rollback pointer resolves to ROLL.DBF file 0, page 1040, offset 106.
	tail, err := hex.DecodeString("08000000000000100400006a00db1202000000")
	if err != nil {
		t.Fatal(err)
	}
	control, ok := decodeDataRowControlTail(append([]byte{0x00, 0x20, 0x00}, tail...))
	if !ok {
		t.Fatal("control tail was not decoded")
	}
	if control.clusterRowID != 8 || control.rollFile != 0 || control.rollPage != 1040 || control.rollOffset != 106 || control.transactionID != 135899 {
		t.Fatalf("unexpected control tail: %+v", control)
	}
	if !control.hasRollbackAddress() {
		t.Fatal("real rollback pointer was treated as a sentinel")
	}

	clean, err := hex.DecodeString("070000000000ffffffff7fffffa91202000000")
	if err != nil {
		t.Fatal(err)
	}
	cleanControl, ok := decodeDataRowControlTail(clean)
	if !ok || cleanControl.hasRollbackAddress() || cleanControl.clusterRowID != 7 || cleanControl.transactionID != 135849 {
		t.Fatalf("unexpected clean control tail: %+v, ok=%t", cleanControl, ok)
	}
}

func TestMetadataState10IsRejectedWithoutHeuristicFallback(t *testing.T) {
	row := []byte{0x00, 0x07, 0x02, 0x2A, 0x00, 0x00, 0x00}
	_, _, _, err := parseDataRowValuesForColumns(row, []columnDef{{
		ColID: 1, Name: "C1", DataType: "INT", Nullable: "Y",
	}}, textDecoder{preferred: "utf-8"}, nil)
	if err == nil || !strings.Contains(err.Error(), "metadata state 10") {
		t.Fatalf("state 10 should remain unsupported, got %v", err)
	}
	_, _, _, err = parseDataRowValues(row, []columnDef{{
		ColID: 1, Name: "C1", DataType: "INT", Nullable: "Y",
	}}, textDecoder{preferred: "utf-8"}, true, nil)
	if err == nil || !strings.Contains(err.Error(), "metadata state 10") {
		t.Fatalf("historical-column fallback accepted state 10: %v", err)
	}
}

func TestDecodeDMDateTime(t *testing.T) {
	var raw [8]byte
	v := uint64(2026) |
		uint64(6)<<15 |
		uint64(18)<<19 |
		uint64(9)<<24 |
		uint64(23)<<29 |
		uint64(20)<<35 |
		uint64(123456)<<41
	binary.LittleEndian.PutUint64(raw[:], v)

	got, err := decodeDMDateTime(raw[:])
	if err != nil {
		t.Fatalf("decodeDMDateTime returned error: %v", err)
	}
	want := "2026-06-18 09:23:20.123456"
	if got != want {
		t.Fatalf("decodeDMDateTime = %q, want %q", got, want)
	}
}

func TestDecodeDMDate(t *testing.T) {
	got, err := decodeDMDate([]byte{0xD0, 0x07, 0x35})
	if err != nil {
		t.Fatalf("decodeDMDate returned error: %v", err)
	}
	if got != "2000-10-06" {
		t.Fatalf("decodeDMDate = %q, want %q", got, "2000-10-06")
	}
}

func TestDecodeDMTime(t *testing.T) {
	var raw [5]byte
	v := uint64(15) |
		uint64(56)<<5 |
		uint64(5)<<11 |
		uint64(123456)<<17
	for i := 0; i < len(raw); i++ {
		raw[i] = byte(v >> (8 * i))
	}
	got, err := decodeDMTime(raw[:])
	if err != nil {
		t.Fatalf("decodeDMTime returned error: %v", err)
	}
	if got != "15:56:05.123456" {
		t.Fatalf("decodeDMTime = %q", got)
	}
}

func TestParseDataRowMidnightTimeIsNotNull(t *testing.T) {
	columns := []columnDef{
		{ColID: 0, Name: "t", DataType: "time", Length: 5, Scale: 6, Nullable: "Y"},
	}
	decoder := textDecoder{preferred: "utf-8"}

	// [2B BE length][1B states][5B TIME] with the state marking the value as
	// present: an all-zero TIME payload is a real midnight value, not NULL.
	present := []byte{0x00, 0x08, 0x00, 0, 0, 0, 0, 0}
	values, _, _, err := parseDataRowValuesWithMetadata(present, columns, decoder, nil)
	if err != nil {
		t.Fatalf("parse present midnight TIME: %v", err)
	}
	if got, want := values[0].value, "00:00:00.000000"; got != want {
		t.Fatalf("midnight TIME = %v, want %q", got, want)
	}

	// The same payload with the NULL state must still decode as NULL.
	null := []byte{0x00, 0x08, 0x03, 0, 0, 0, 0, 0}
	values, _, _, err = parseDataRowValuesWithMetadata(null, columns, decoder, nil)
	if err != nil {
		t.Fatalf("parse NULL TIME: %v", err)
	}
	if values[0].value != nil {
		t.Fatalf("NULL TIME = %v, want nil", values[0].value)
	}
}

func TestDecodeDMNanosecondTimestamp(t *testing.T) {
	raw := make([]byte, 9)
	date := uint32(2026) | uint32(7)<<15 | uint32(13)<<19
	raw[0] = byte(date)
	raw[1] = byte(date >> 8)
	raw[2] = byte(date >> 16)
	timeBits := uint64(12) | uint64(34)<<5 | uint64(56)<<11 | uint64(123456000)<<17
	for i := 0; i < 6; i++ {
		raw[3+i] = byte(timeBits >> (8 * i))
	}
	got, err := decodeDMDateTimeWithPrecision(raw, 9)
	if err != nil {
		t.Fatal(err)
	}
	if got != "2026-07-13 12:34:56.123456000" {
		t.Fatalf("nanosecond timestamp = %q", got)
	}
}

func TestDecodeAllDMIntervalQualifiers(t *testing.T) {
	yearMonth := func(year, month int32) []byte {
		raw := make([]byte, 12)
		binary.LittleEndian.PutUint32(raw[0:4], uint32(year))
		binary.LittleEndian.PutUint32(raw[4:8], uint32(month))
		binary.LittleEndian.PutUint16(raw[8:10], uint16(4<<4))
		return raw
	}
	dayTime := func(day, hour, minute, second, microsecond int32) []byte {
		raw := make([]byte, 24)
		for i, value := range []int32{day, hour, minute, second, microsecond} {
			binary.LittleEndian.PutUint32(raw[i*4:i*4+4], uint32(value))
		}
		binary.LittleEndian.PutUint16(raw[20:22], uint16(4<<4|6))
		return raw
	}
	tests := []struct {
		typ  string
		raw  []byte
		want string
	}{
		{"INTERVAL YEAR", yearMonth(12, 0), "12"},
		{"INTERVAL MONTH", yearMonth(0, -25), "-25"},
		{"INTERVAL YEAR TO MONTH", yearMonth(12, 11), "12-11"},
		{"INTERVAL DAY", dayTime(123, 0, 0, 0, 0), "123"},
		{"INTERVAL HOUR", dayTime(0, -49, 0, 0, 0), "-49"},
		{"INTERVAL MINUTE", dayTime(0, 0, 125, 0, 0), "125"},
		{"INTERVAL SECOND", dayTime(0, 0, 0, -125, -123456), "-125.123456"},
		{"INTERVAL DAY TO HOUR", dayTime(12, 23, 0, 0, 0), "12 23"},
		{"INTERVAL DAY TO MINUTE", dayTime(-12, -23, -59, 0, 0), "-12 23:59"},
		{"INTERVAL DAY TO SECOND", dayTime(12, 23, 59, 58, 123456), "12 23:59:58.123456"},
		{"INTERVAL HOUR TO MINUTE", dayTime(0, -49, -59, 0, 0), "-49:59"},
		{"INTERVAL HOUR TO SECOND", dayTime(0, 49, 59, 58, 123456), "49:59:58.123456"},
		{"INTERVAL MINUTE TO SECOND", dayTime(0, 0, -125, -58, -123456), "-125:58.123456"},
	}
	for _, test := range tests {
		var got string
		if isYearMonthIntervalDataType(test.typ) {
			got = decodeDMIntervalYearToMonth(test.raw, test.typ)
		} else {
			got = decodeDMIntervalDayToSecond(test.raw, test.typ)
		}
		if got != test.want {
			t.Fatalf("%s = %q, want %q", test.typ, got, test.want)
		}
	}
}

func TestDecodeVerifiedJSONBAtoms(t *testing.T) {
	tests := []struct {
		raw  string
		want string
	}{
		{"f1d83401000000c02d29da84000000000100001000000060", "null"},
		{"f1d83401000000c03e21f2090000000001000010060000203132332e3435", "123.45"},
		{"f1d83401000000c024a1cb310000000002000040140000900800001001000000000000000200000000000000", "[1,2]"},
		{"f1d83401000000c0c911cb9800000000030000201d0000b0010000300100003000000040010000300000006061786263", `{"a":"x","b":false,"c":null}`},
	}
	for _, test := range tests {
		raw, err := hex.DecodeString(test.raw)
		if err != nil {
			t.Fatal(err)
		}
		got, err := decodeDMJSONB(raw, textDecoder{preferred: "utf-8"})
		if err != nil {
			t.Fatalf("decodeDMJSONB(%s): %v", test.raw, err)
		}
		if string(got) != test.want {
			t.Fatalf("decodeDMJSONB(%s) = %q, want %q", test.raw, got, test.want)
		}
	}
}

func TestDataFileKeyFromPageHeader(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	head := make([]byte, 16)
	binary.LittleEndian.PutUint16(head[0:], 4)
	binary.LittleEndian.PutUint16(head[2:], 0)
	binary.LittleEndian.PutUint32(head[4:], 0)
	if err := os.WriteFile(path, head, 0644); err != nil {
		t.Fatal(err)
	}

	got, ok := dataFileKeyFromPageHeader(path)
	if !ok {
		t.Fatal("dataFileKeyFromPageHeader returned !ok")
	}
	if got.groupID != 4 || got.fileID != 0 {
		t.Fatalf("dataFileKeyFromPageHeader = %+v", got)
	}
}

func TestCandidateMatchesFileUsesDictionarySegmentRange(t *testing.T) {
	info := dataTableInfo{
		table: dictionaryObject{ID: 1024, Owner: "SY", Name: "t"},
		segment: tableSegment{
			fileID:       0,
			headerPage:   176,
			blocks:       16,
			tablespaceID: 4,
		},
		segmentKnown: true,
	}
	file := dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}}
	if !candidateMatchesFile(info, file, 176) || !candidateMatchesFile(info, file, 191) {
		t.Fatal("candidate should match pages inside segment range")
	}
	if candidateMatchesFile(info, file, 175) || candidateMatchesFile(info, file, 192) {
		t.Fatal("candidate should not match pages outside segment range")
	}
	if candidateMatchesFile(info, dataFileRef{key: dataFileKey{groupID: 4, fileID: 1}}, 176) {
		t.Fatal("candidate should not match a different file")
	}
}

func TestCandidateMatchesFileKeepsMultiExtentPagesInSameFile(t *testing.T) {
	info := dataTableInfo{
		table: dictionaryObject{ID: 1033, Owner: "SYSDBA", Name: "T"},
		segment: tableSegment{
			fileID:       0,
			headerPage:   32,
			blocks:       32,
			extents:      2,
			tablespaceID: 4,
		},
		segmentKnown: true,
	}
	file := dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}}
	if !candidateMatchesFile(info, file, 160) {
		t.Fatal("multi-extent table should keep pages in the same file")
	}
	if candidateMatchesFile(info, dataFileRef{key: dataFileKey{groupID: 5, fileID: 0}}, 160) {
		t.Fatal("multi-extent table should still reject a different tablespace")
	}
	if candidateMatchesFile(info, dataFileRef{key: dataFileKey{groupID: 4, fileID: 1}}, 160) {
		t.Fatal("multi-extent table should still reject a different file")
	}
}

func TestBuildStoragePagePlanWalksLeafChainFromRoot(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, 32*8192)
	putTestDMPageHeader(raw[16*8192:17*8192], 4, 0, 16, dmPageKindBTreeLeaf, 1038)
	putTestDMPageRef(raw[16*8192:17*8192], dmPageNextRefOff, 0, 17)
	putTestDMPageHeader(raw[17*8192:18*8192], 4, 0, 17, dmPageKindBTreeLeaf, 1038)
	putTestDMNullPageRef(raw[17*8192:18*8192], dmPageNextRefOff)
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}

	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, 8192)
	plan := buildStoragePagePlan(indexDef{ID: 1038, GroupID: 4, RootFile: 0, RootPage: 16}, cache)
	if len(plan) != 2 {
		t.Fatalf("expected 2 planned pages, got %d", len(plan))
	}
	if !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 16}] || !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 17}] {
		t.Fatalf("unexpected page plan: %+v", plan)
	}
}

func TestBuildStoragePagePlanDescendsInternalRoot(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, 64*8192)
	putTestDMPageHeader(raw[16*8192:17*8192], 4, 0, 16, dmPageKindBTreeRoot, 1041)
	binary.LittleEndian.PutUint32(raw[16*8192+dmBTreeLeftmostChildOff:], 20)
	putTestDMPageHeader(raw[20*8192:21*8192], 4, 0, 20, dmPageKindBTreeLeaf, 1041)
	putTestDMPageRef(raw[20*8192:21*8192], dmPageNextRefOff, 0, 21)
	putTestDMPageHeader(raw[21*8192:22*8192], 4, 0, 21, dmPageKindBTreeLeaf, 1041)
	putTestDMNullPageRef(raw[21*8192:22*8192], dmPageNextRefOff)
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}

	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, 8192)
	plan := buildStoragePagePlan(indexDef{ID: 1041, GroupID: 4, RootFile: 0, RootPage: 16}, cache)
	if len(plan) != 2 {
		t.Fatalf("expected 2 planned leaf pages, got %d", len(plan))
	}
	if plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 16}] {
		t.Fatalf("internal root should not be exported as a data page: %+v", plan)
	}
	if !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 20}] || !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 21}] {
		t.Fatalf("unexpected page plan: %+v", plan)
	}
}

func TestBuildStoragePagePlanUsesInternalNextWhenLeftmostChildIsMissing(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, 64*8192)
	putTestDMPageHeader(raw[16*8192:17*8192], 4, 0, 16, dmPageKindBTreeRoot, 1041)
	binary.LittleEndian.PutUint32(raw[16*8192+dmBTreeLeftmostChildOff:], 99)
	putTestDMPageRef(raw[16*8192:17*8192], dmPageNextRefOff, 0, 18)
	putTestDMPageHeader(raw[18*8192:19*8192], 4, 0, 18, dmPageKindBTreeRoot, 1041)
	binary.LittleEndian.PutUint32(raw[18*8192+dmBTreeLeftmostChildOff:], 20)
	putTestDMPageHeader(raw[20*8192:21*8192], 4, 0, 20, dmPageKindBTreeLeaf, 1041)
	putTestDMPageRef(raw[20*8192:21*8192], dmPageNextRefOff, 0, 21)
	putTestDMPageHeader(raw[21*8192:22*8192], 4, 0, 21, dmPageKindBTreeLeaf, 1041)
	putTestDMNullPageRef(raw[21*8192:22*8192], dmPageNextRefOff)
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}

	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, 8192)
	plan := buildStoragePagePlan(indexDef{ID: 1041, GroupID: 4, RootFile: 0, RootPage: 16}, cache)
	if len(plan) != 2 {
		t.Fatalf("expected 2 planned leaf pages, got %d", len(plan))
	}
	if plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 16}] || plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 18}] {
		t.Fatalf("internal pages should not be exported as data pages: %+v", plan)
	}
	if !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 20}] || !plan[dataPageRef{key: dataFileKey{groupID: 4, fileID: 0}, pageNo: 21}] {
		t.Fatalf("unexpected page plan: %+v", plan)
	}
}

func TestBuildStoragePagePlanRejectsBrokenLeafChain(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, 32*8192)
	putTestDMPageHeader(raw[16*8192:17*8192], 4, 0, 16, dmPageKindBTreeLeaf, 1041)
	putTestDMPageRef(raw[16*8192:17*8192], dmPageNextRefOff, 0, 17)
	putTestDMPageHeader(raw[17*8192:18*8192], 4, 0, 17, dmPageKindBTreeLeaf, 9999)
	putTestDMNullPageRef(raw[17*8192:18*8192], dmPageNextRefOff)
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}

	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, 8192)
	plan, reason := buildStoragePagePlanDetailed(indexDef{ID: 1041, GroupID: 4, RootFile: 0, RootPage: 16}, cache)
	if len(plan) != 0 {
		t.Fatalf("broken leaf chain must not return a partial plan: %+v", plan)
	}
	if !strings.Contains(reason, "storage_id=9999") {
		t.Fatalf("unexpected broken-chain reason %q", reason)
	}
}

func TestBuildStoragePagePlanReportsMissingDataFileIdentity(t *testing.T) {
	cache := newDataFilePageCache(nil, 8192)
	plan, reason := buildStoragePagePlanDetailed(indexDef{ID: 1041, GroupID: 9, RootFile: 2, RootPage: 16}, cache)
	if len(plan) != 0 || reason != "data file group=9 file=2 is unavailable" {
		t.Fatalf("plan=%v reason=%q", plan, reason)
	}
}

func TestDataFileRefsFromSourcesRejectsDuplicateIdentity(t *testing.T) {
	raw := make([]byte, 8192)
	sources := []OfflineDataSource{
		{GroupID: 5, FileID: 0, Path: "+DATA/DB/A.DBF", Reader: bytes.NewReader(raw)},
		{GroupID: 5, FileID: 0, Path: "+DATA/DB/B.DBF", Reader: bytes.NewReader(raw)},
	}
	if _, err := dataFileRefsFromSources(sources); err == nil || !strings.Contains(err.Error(), "duplicate data file identity group=5 file=0") {
		t.Fatalf("unexpected duplicate identity error: %v", err)
	}
}

func TestExportDataReadsOnlyPlannedPages(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	mainPath := filepath.Join(dir, "MAIN.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555433
	raw := make([]byte, 128*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(raw[96*8192:97*8192], 4, 0, 96, storageID, 100)
	putTestDMPageRef(raw[96*8192:97*8192], dmPageNextRefOff, 0, 97)
	putTestIntDataPage(raw[97*8192:98*8192], 4, 0, 97, storageID, 101)
	putTestDMNullPageRef(raw[97*8192:98*8192], dmPageNextRefOff)
	if err := os.WriteFile(mainPath, raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 96, 0, 0)
	result, err := ExportData(DataExportOptions{
		SystemPath:  systemPath,
		DataDir:     dir,
		OutputPath:  filepath.Join(dir, "planned.sql"),
		OwnerFilter: "APP",
		TableFilter: "APP.T_PLAN",
		Charset:     "utf-8",
		Dictionary:  dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.PlannedPages != 2 || result.DirectPagesRead != result.PlannedPages || result.FallbackPagesScanned != 0 || result.PagesScanned != 2 {
		t.Fatalf("unexpected page counters: planned=%d direct=%d fallback=%d total=%d", result.PlannedPages, result.DirectPagesRead, result.FallbackPagesScanned, result.PagesScanned)
	}
	if result.DataFileCount != 1 || result.RowsExported != 2 || len(result.FallbackReasons) != 0 {
		t.Fatalf("unexpected export result: %+v", result)
	}
	if sql := readDataExportTestFile(t, result.OutputPath); !strings.Contains(sql, "VALUES (100)") || !strings.Contains(sql, "VALUES (101)") {
		t.Fatalf("planned export did not recover the row: %q", sql)
	}
}

func TestExportDataStorageFallbackScansOnlyMatchingGroup(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555434
	mainRaw := make([]byte, 8*8192)
	putTestDMPageHeader(mainRaw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(mainRaw[3*8192:4*8192], 4, 0, 3, storageID, 200)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), mainRaw, 0644); err != nil {
		t.Fatal(err)
	}
	otherRaw := make([]byte, 13*8192)
	putTestDMPageHeader(otherRaw[:8192], 5, 0, 0, 0, 0)
	putTestIntDataPage(otherRaw[4*8192:5*8192], 5, 0, 4, storageID, 999)
	if err := os.WriteFile(filepath.Join(dir, "OTHER.DBF"), otherRaw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 7, 0, 0)
	result, err := ExportData(DataExportOptions{
		SystemPath:  systemPath,
		DataDir:     dir,
		OutputPath:  filepath.Join(dir, "storage-fallback.sql"),
		OwnerFilter: "APP",
		TableFilter: "APP.T_PLAN",
		Charset:     "utf-8",
		Dictionary:  dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.PlannedPages != 0 || result.DirectPagesRead != 0 || result.FallbackPagesScanned != 8 || result.DataFileCount != 1 {
		t.Fatalf("storage fallback escaped its group: %+v", result)
	}
	if sql := readDataExportTestFile(t, result.OutputPath); !strings.Contains(sql, "VALUES (200)") || strings.Contains(sql, "VALUES (999)") {
		t.Fatalf("unexpected storage fallback rows: %q", sql)
	}
}

func TestExportDataUsesSegmentAfterStorageFallbackMiss(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555435
	raw := make([]byte, 8*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(raw[4*8192:5*8192], 4, 0, 4, 44556677, 300)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 7, 4, 1)
	result, err := ExportData(DataExportOptions{
		SystemPath:  systemPath,
		DataDir:     dir,
		OutputPath:  filepath.Join(dir, "segment-fallback.sql"),
		OwnerFilter: "APP",
		TableFilter: "APP.T_PLAN",
		Charset:     "utf-8",
		Dictionary:  dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.FallbackPagesScanned != 9 || result.RowsExported != 1 {
		t.Fatalf("segment fallback counters/result are wrong: %+v", result)
	}
	if sql := readDataExportTestFile(t, result.OutputPath); !strings.Contains(sql, "VALUES (300)") {
		t.Fatalf("segment fallback did not recover the row: %q", sql)
	}
	foundReason := false
	for _, reason := range result.FallbackReasons {
		if strings.Contains(reason, "scanning segment") {
			foundReason = true
		}
	}
	if !foundReason {
		t.Fatalf("segment fallback reason is missing: %v", result.FallbackReasons)
	}
}

func TestExportDataRecoveryModeIsTheFullFileScanPath(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555436
	mainRaw := make([]byte, 8*8192)
	putTestDMPageHeader(mainRaw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(mainRaw[3*8192:4*8192], 4, 0, 3, storageID, 400)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), mainRaw, 0644); err != nil {
		t.Fatal(err)
	}
	otherRaw := make([]byte, 13*8192)
	putTestDMPageHeader(otherRaw[:8192], 5, 0, 0, 0, 0)
	if err := os.WriteFile(filepath.Join(dir, "OTHER.DBF"), otherRaw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 3, 0, 0)
	result, err := ExportData(DataExportOptions{
		SystemPath:   systemPath,
		DataDir:      dir,
		OutputPath:   filepath.Join(dir, "recovery.sql"),
		OwnerFilter:  "APP",
		TableFilter:  "APP.T_PLAN",
		Charset:      "utf-8",
		RecoveryMode: true,
		Dictionary:   dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.PlannedPages != 0 || result.DirectPagesRead != 0 || result.FallbackPagesScanned != 21 || result.DataFileCount != 2 || result.RowsExported != 1 {
		t.Fatalf("recovery mode did not use the full-file path: %+v", result)
	}
	if len(result.FallbackReasons) != 1 || !strings.Contains(result.FallbackReasons[0], "full-file residual") {
		t.Fatalf("recovery fallback reason is missing: %v", result.FallbackReasons)
	}
	if len(result.RecoverySources) != 1 || result.RecoverySources[0].Heuristic {
		t.Fatalf("dictionary-owned recovery source evidence is wrong: %+v", result.RecoverySources)
	}
}

func TestExportDataRecoveryModeRecordsOrphanSourceEvidence(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const currentStorageID = 33555438
	const orphanStorageID = 44556678
	raw := make([]byte, 8*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(raw[3*8192:4*8192], 4, 0, 3, orphanStorageID, 450)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, currentStorageID, 7, 0, 0)
	result, err := ExportData(DataExportOptions{
		SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, "orphan-recovery.sql"),
		OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", RecoveryMode: true, Dictionary: dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.RowsExported != 1 || len(result.RecoverySources) != 1 {
		t.Fatalf("orphan recovery result/evidence is wrong: %+v", result)
	}
	source := result.RecoverySources[0]
	if !source.Heuristic || source.Owner != "APP" || source.Name != "T_PLAN" || source.GroupID != 4 || source.FileID != 0 || source.StorageID != orphanStorageID || source.FirstPage != 3 || source.LastPage != 3 || source.Pages != 1 || source.RowsExported != 1 {
		t.Fatalf("unexpected orphan recovery source: %+v", source)
	}
	foundWarning := false
	for _, reason := range result.FallbackReasons {
		if strings.Contains(reason, "orphan storage recovery is heuristic") {
			foundWarning = true
		}
	}
	if !foundWarning {
		t.Fatalf("orphan attribution warning is missing: %v", result.FallbackReasons)
	}
	if sql := readDataExportTestFile(t, result.OutputPath); !strings.Contains(sql, "VALUES (450)") {
		t.Fatalf("orphan recovery did not export the accepted row: %q", sql)
	}
}

func TestExportDataRecoveryDoesNotClaimAnotherDictionaryTableStorage(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const targetStorageID = 33555439
	const otherStorageID = 33555440
	raw := make([]byte, 8*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	putTestIntDataPage(raw[3*8192:4*8192], 4, 0, 3, otherStorageID, 999)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, targetStorageID, 7, 0, 0)
	dict.Tables = append(dict.Tables, DictionaryTable{
		ID: 1002, Owner: "APP", Name: "T_OTHER", ColumnCount: 1,
		Tablespace: "MAIN", GroupID: 4, Storage: "CLUSTERBTR", StorageID: otherStorageID, RootFile: 0, RootPage: 3,
	})
	dict.Columns = append(dict.Columns, DictionaryColumn{
		TableID: 1002, TableOwner: "APP", TableName: "T_OTHER", ColID: 1, Name: "ID", DataType: "INT", Nullable: "N",
	})
	result, err := ExportData(DataExportOptions{
		SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, "target-recovery.sql"),
		OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", RecoveryMode: true, Dictionary: dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	if result.RowsExported != 0 || len(result.RecoverySources) != 0 {
		t.Fatalf("target table claimed another live dictionary storage: %+v", result)
	}
	if sql := readDataExportTestFile(t, result.OutputPath); strings.Contains(sql, "VALUES (999)") {
		t.Fatalf("another table's row leaked into target recovery: %q", sql)
	}
}

func TestBuildOrphanRecoveryCandidatesRequiresOneTargetTable(t *testing.T) {
	table := dictionaryObject{ID: 1001, Owner: "APP", Name: "T_PLAN"}
	candidates, reason := buildOrphanRecoveryCandidates(map[uint32]dataTableInfo{
		1001: {table: table, storageUnitID: 1001, recoveryGroupID: 4},
		2001: {table: table, storageUnitID: 2001, recoveryGroupID: 4},
	})
	if reason != "" || len(candidates) != 1 || !candidates[0].orphanRecovery || candidates[0].storageUnitID != table.ID {
		t.Fatalf("partition storage units should collapse to one target candidate: candidates=%+v reason=%q", candidates, reason)
	}

	other := dictionaryObject{ID: 1002, Owner: "APP", Name: "T_OTHER"}
	candidates, reason = buildOrphanRecoveryCandidates(map[uint32]dataTableInfo{
		1001: {table: table, storageUnitID: 1001},
		1002: {table: other, storageUnitID: 1002},
	})
	if len(candidates) != 0 || !strings.Contains(reason, "disabled for 2 target tables") {
		t.Fatalf("ambiguous orphan recovery should be disabled: candidates=%+v reason=%q", candidates, reason)
	}
}

func TestOrphanRecoveryCandidateRequiresConsistentRowSample(t *testing.T) {
	page := make([]byte, 8192)
	putTestDMPageHeader(page, 4, 0, 3, dmPageKindRowData, 44556679)
	putTestRow(page, dataRowAreaStart, 7, 0)
	binary.LittleEndian.PutUint32(page[dataRowAreaStart+3:], 451)
	putTestRow(page, dataRowAreaStart+7, 3, 0)
	rows := []locatedDataRow{
		{offset: dataRowAreaStart, length: 7, fromSlot: true},
		{offset: dataRowAreaStart + 7, length: 3, fromSlot: true},
	}
	candidate := dataTableInfo{
		table:           dictionaryObject{ID: 1001, Owner: "APP", Name: "T_PLAN"},
		columns:         []columnDef{{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"}},
		recoveryMode:    true,
		orphanRecovery:  true,
		recoveryGroupID: 4,
	}
	if _, ok := selectDataPageCandidate([]dataTableInfo{candidate}, dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}}, 3, page, 8192, rows, textDecoder{preferred: "utf-8"}); ok {
		t.Fatal("one parseable row must not attribute an inconsistent orphan page")
	}
	candidate.orphanRecovery = false
	if _, ok := selectDataPageCandidate([]dataTableInfo{candidate}, dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}}, 3, page, 8192, rows, textDecoder{preferred: "utf-8"}); !ok {
		t.Fatal("dictionary-owned recovery candidate should retain the existing tolerant row probe")
	}
}

func TestSecondaryIndexStorageIDSet(t *testing.T) {
	objects := map[uint32]dictionaryObject{
		101: {ID: 101, Type: "TABOBJ", Subtype: "INDEX"},
		102: {ID: 102, Type: "TABOBJ", Subtype: "INDEX"},
	}
	indexes := map[uint32]indexDef{
		101: {ID: 101, Flag: 1, KeyNum: 0},
		102: {ID: 102, Flag: 0, KeyNum: 1},
		103: {ID: 103, Flag: 0, KeyNum: 1},
	}
	got := secondaryIndexStorageIDSet(objects, indexes)
	if got[101] || !got[102] || got[103] {
		t.Fatalf("unexpected secondary index storage ids: %+v", got)
	}
}

func TestExportDataKeepsPhysicalHoleAndDeletedRowRecoveryOnly(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555437
	raw := make([]byte, 8*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	page := raw[3*8192 : 4*8192]
	putTestDMPageHeader(page, 4, 0, 3, dmPageKindRowData, storageID)
	liveOff := dataRowAreaStart
	deletedOff := liveOff + 7
	holeOff := deletedOff + 7
	for off, value := range map[int]int32{liveOff: 400, deletedOff: 401, holeOff: 402} {
		binary.BigEndian.PutUint16(page[off:], 7)
		page[off+2] = 0
		binary.LittleEndian.PutUint32(page[off+3:], uint32(value))
	}
	binary.BigEndian.PutUint16(page[deletedOff:], dataRowDeletedMask|7)
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 2)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], uint16(holeOff+7))
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
	putTestDataPageSlot(page, len(page), 2, 1, liveOff)
	putTestDataPageSlot(page, len(page), 2, 2, deletedOff)
	putTestDMNullPageRef(page, dmPageNextRefOff)
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 3, 0, 0)

	normal, err := ExportData(DataExportOptions{
		SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, "normal.sql"),
		OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", Dictionary: dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	normalSQL := readDataExportTestFile(t, normal.OutputPath)
	if normal.RowsExported != 1 || !strings.Contains(normalSQL, "VALUES (400)") || strings.Contains(normalSQL, "VALUES (401)") || strings.Contains(normalSQL, "VALUES (402)") {
		t.Fatalf("normal unload escaped the live slot directory: result=%+v sql=%q", normal, normalSQL)
	}

	recovery, err := ExportData(DataExportOptions{
		SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, "recovery-rows.sql"),
		OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", RecoveryMode: true, Dictionary: dict,
	})
	if err != nil {
		t.Fatal(err)
	}
	recoverySQL := readDataExportTestFile(t, recovery.OutputPath)
	if recovery.RowsExported != 3 {
		t.Fatalf("recovery rows=%d, want 3: %q", recovery.RowsExported, recoverySQL)
	}
	for _, value := range []string{"VALUES (400)", "VALUES (401)", "VALUES (402)"} {
		if !strings.Contains(recoverySQL, value) {
			t.Fatalf("recovery output is missing %s: %q", value, recoverySQL)
		}
	}
}

func TestCandidateMatchesFileUsesPagePlanBeforeSegmentRange(t *testing.T) {
	info := dataTableInfo{
		table: dictionaryObject{ID: 1038, Owner: "SYSDBA", Name: "BIN_TEST2"},
		pagePlan: map[dataPageRef]bool{
			{key: dataFileKey{groupID: 5, fileID: 0}, pageNo: 144}: true,
		},
		pagePlanKnown: true,
		segment: tableSegment{
			fileID:       0,
			headerPage:   16,
			blocks:       16,
			tablespaceID: 4,
		},
		segmentKnown: true,
	}
	file := dataFileRef{key: dataFileKey{groupID: 5, fileID: 0}}
	if !candidateMatchesFile(info, file, 144) {
		t.Fatal("exact page plan should take precedence over stale segment identity and range metadata")
	}
	if candidateMatchesFile(info, file, 145) {
		t.Fatal("page outside the exact page plan should not match")
	}
	if candidateMatchesFile(info, dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}}, 144) {
		t.Fatal("the exact page reference should reject a different tablespace")
	}
}

func TestCandidateMatchesFileRecoveryIgnoresCurrentSegmentWindow(t *testing.T) {
	info := dataTableInfo{
		table:           dictionaryObject{ID: 1066, Owner: "USERS1", Name: "T_TEST"},
		recoveryMode:    true,
		recoveryGroupID: 6,
		segment: tableSegment{
			fileID:       0,
			headerPage:   16,
			blocks:       16,
			extents:      1,
			tablespaceID: 6,
		},
		segmentKnown: true,
	}
	file := dataFileRef{key: dataFileKey{groupID: 6, fileID: 0}}
	if !candidateMatchesFile(info, file, 180) {
		t.Fatal("recovery mode should allow residual pages outside the current post-truncate segment window")
	}
	if candidateMatchesFile(info, dataFileRef{key: dataFileKey{groupID: 7, fileID: 0}}, 180) {
		t.Fatal("recovery mode should still reject a different tablespace when group id is known")
	}
}

func TestResolveDataFilesWithoutControlFileUsesPageHeaders(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	head := make([]byte, 16)
	binary.LittleEndian.PutUint16(head[0:], 4)
	binary.LittleEndian.PutUint16(head[2:], 0)
	binary.LittleEndian.PutUint32(head[4:], 0)
	if err := os.WriteFile(path, head, 0644); err != nil {
		t.Fatal(err)
	}

	files, err := resolveDataFiles("", "", dir)
	if err != nil {
		t.Fatalf("resolveDataFiles returned error: %v", err)
	}
	if len(files) != 1 {
		t.Fatalf("resolveDataFiles returned %d files, want 1", len(files))
	}
	if files[0].key.groupID != 4 || files[0].key.fileID != 0 || files[0].path != path {
		t.Fatalf("unexpected data file ref: %+v", files[0])
	}
}

func TestDecodeDMNumber(t *testing.T) {
	tests := []struct {
		raw  []byte
		want string
	}{
		{raw: []byte{0xC3, 0x03, 0x33}, want: "25000"},
		{raw: []byte{0xC3, 0x02, 0x51}, want: "18000"},
		{raw: []byte{0xC2, 0x0D, 0x23}, want: "1234"},
		{raw: []byte{0x3A, 0x03, 0x19, 0x2F, 0x45, 0x5B, 0x24, 0x3A, 0x50, 0x66}, want: "-9876543210.654321"},
		{raw: []byte{0x41, 0x64, 0x66}, want: "-0.000001"},
		{raw: []byte{0x80}, want: "0"},
	}
	for _, tt := range tests {
		got, ok := decodeDMNumber(tt.raw)
		if !ok {
			t.Fatalf("decodeDMNumber(% X) returned !ok", tt.raw)
		}
		if got != tt.want {
			t.Fatalf("decodeDMNumber(% X) = %q, want %q", tt.raw, got, tt.want)
		}
	}
}

func TestRenderInsertForMixedDateAndVariableRow(t *testing.T) {
	row := []byte{
		0x00, 0x0D, 0x00,
		0xD0, 0x07, 0x35,
		0x82, 0xC1, 0x02,
		0x83, 'A', 'B', 'C',
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "T"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "NUMBER(11)"},
			{ColID: 2, Name: "NAME", DataType: "VARCHAR2"},
			{ColID: 3, Name: "BIRTHDAY", DataType: "DATE"},
		},
	}
	sql, start, end, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 3 || end != len(row) {
		t.Fatalf("unexpected data bounds: %d..%d", start, end)
	}
	if !strings.Contains(sql, "INSERT INTO SYSDBA.T (ID, NAME, BIRTHDAY) VALUES (1, 'ABC', DATE '2000-10-06');") {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertUsesExplicitNullMetadata(t *testing.T) {
	row := []byte{
		0x00, 0x0D,
		0xCC,
		0x0A, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x00, 0x00,
		0x85, 'A', 'l', 'i', 'c', 'e',
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "APP", Name: "T_NULL_META"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"},
			{ColID: 2, Name: "N1", DataType: "INT", Nullable: "Y"},
			{ColID: 3, Name: "NAME", DataType: "VARCHAR", Nullable: "Y"},
			{ColID: 4, Name: "NOTE", DataType: "VARCHAR", Nullable: "Y"},
		},
	}
	sql, start, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 3 {
		t.Fatalf("data start = %d, want 3", start)
	}
	want := `INSERT INTO APP.T_NULL_META (ID, N1, NAME, NOTE) VALUES (10, NULL, 'Alice', NULL);`
	if !strings.Contains(sql, want) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForScalarTypes(t *testing.T) {
	var timeRaw [5]byte
	tv := uint64(15) | uint64(56)<<5 | uint64(5)<<11 | uint64(123456)<<17
	for i := 0; i < len(timeRaw); i++ {
		timeRaw[i] = byte(tv >> (8 * i))
	}
	row := []byte{0x00, 0x16, 0x00}
	var buf [8]byte
	binary.LittleEndian.PutUint32(buf[:4], math.Float32bits(float32(1.25)))
	row = append(row, buf[:4]...)
	binary.LittleEndian.PutUint64(buf[:8], math.Float64bits(3.5))
	row = append(row, buf[:8]...)
	row = append(row, timeRaw[:]...)
	info := dataTableInfo{
		table: dictionaryObject{Owner: "APP", Name: "T_TYPES"},
		columns: []columnDef{
			{ColID: 1, Name: "R", DataType: "REAL", Nullable: "N"},
			{ColID: 2, Name: "D", DataType: "DOUBLE", Nullable: "N"},
			{ColID: 3, Name: "T", DataType: "TIME", Nullable: "N"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if !strings.Contains(sql, "VALUES (1.25, 3.5, TIME '15:56:05.123456');") {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestDecodeAdditionalFixedScalarTypes(t *testing.T) {
	rowIDRaw := make([]byte, 12)
	rowIDRaw[11] = 1
	intervalYM := make([]byte, 12)
	binary.LittleEndian.PutUint32(intervalYM[0:4], uint32(12))
	binary.LittleEndian.PutUint32(intervalYM[4:8], uint32(11))
	binary.LittleEndian.PutUint32(intervalYM[8:12], uint32((4<<4)|(1<<8)))

	tests := []struct {
		column columnDef
		raw    []byte
		want   string
	}{
		{column: columnDef{Name: "B", DataType: "BIT", Nullable: "N"}, raw: []byte{9}, want: "1"},
		{column: columnDef{Name: "Y", DataType: "BYTE", Nullable: "N"}, raw: []byte{0x88}, want: "-120"},
		{column: columnDef{Name: "BF", DataType: "BINARY_FLOAT", Nullable: "N"}, raw: []byte{0x00, 0x00, 0xA0, 0x3F}, want: "1.25"},
		{column: columnDef{Name: "I", DataType: "INTERVAL YEAR TO MONTH", Nullable: "N"}, raw: intervalYM, want: "12-11"},
		{column: columnDef{Name: "R", DataType: "ROWID", Nullable: "N"}, raw: rowIDRaw, want: "AAAAAAAAAAAAAAAAAB"},
	}
	for _, test := range tests {
		value, next, err := parseFixedDataValue(test.column, test.raw, 0)
		if err != nil {
			t.Fatalf("parseFixedDataValue(%s) failed: %v", test.column.DataType, err)
		}
		if next != len(test.raw) || fmt.Sprintf("%v", value) != test.want {
			t.Fatalf("parseFixedDataValue(%s) = %v next=%d, want %s next=%d", test.column.DataType, value, next, test.want, len(test.raw))
		}
	}
}

func TestDecodeVerifiedROWIDLayout(t *testing.T) {
	tests := []struct {
		raw  string
		want string
	}{
		{raw: "000000000000000000000001", want: "AAAAAAAAAAAAAAAAAB"},
		{raw: "000100000002000000000032", want: "AAABAAAAACAAAAAAAy"},
		{raw: "ffff0000fffeffffffffffff", want: "AP//AAAP/+////////"},
		{raw: "00050000303900003ade68b1", want: "AAAFAAADA5AAA63mix"},
		{raw: "010000000101000100000001", want: "AAEAAAAAEBAAEAAAAB"},
	}
	for _, test := range tests {
		raw, err := hex.DecodeString(test.raw)
		if err != nil {
			t.Fatal(err)
		}
		if got := decodeDMRowID(raw); got != test.want {
			t.Fatalf("decodeDMRowID(%s) = %q, want %q", test.raw, got, test.want)
		}
	}
}

func TestBinaryIsFixedWidthAndDoesNotShiftFollowingValues(t *testing.T) {
	col := columnDef{Name: "B", DataType: "BINARY", Length: 8, Nullable: "N"}
	if isVariableDataType(col.DataType) {
		t.Fatal("BINARY must use fixed-width row storage")
	}
	if got := fixedDataSizeForColumn(col); got != 8 {
		t.Fatalf("fixed BINARY size = %d, want 8", got)
	}
	raw := []byte{0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x83, 0xAA, 0xBB, 0xCC}
	value, next, err := parseFixedDataValue(col, raw, 0)
	if err != nil {
		t.Fatal(err)
	}
	if next != 8 || hex.EncodeToString(value.(dmBinary)) != "0011223344556677" {
		t.Fatalf("fixed BINARY value=%x next=%d", value, next)
	}
	value, end, err := readVariableDataValue(columnDef{Name: "V", DataType: "VARBINARY"}, raw, next, textDecoder{}, nil)
	if err != nil {
		t.Fatal(err)
	}
	if end != len(raw) || hex.EncodeToString(value.(dmBinary)) != "aabbcc" {
		t.Fatalf("following VARBINARY value=%x end=%d", value, end)
	}
}

func TestRAWUsesVariableBinaryStorage(t *testing.T) {
	if !isBinaryDataType("RAW") || !isVariableBinaryDataType("RAW") {
		t.Fatal("RAW must use VARBINARY-compatible row storage")
	}
	raw := []byte{0x83, 0x00, 0xFF, 0x10}
	value, end, err := readVariableDataValue(columnDef{Name: "R", DataType: "RAW"}, raw, 0, textDecoder{}, nil)
	if err != nil {
		t.Fatal(err)
	}
	got, ok := value.(dmBinary)
	if !ok || !bytes.Equal(got, []byte{0x00, 0xFF, 0x10}) || end != len(raw) {
		t.Fatalf("RAW value=%x end=%d", value, end)
	}
}

func TestDMPFieldEncodingForVerifiedScalarTypes(t *testing.T) {
	charset, err := dmpCharsetForDataExport("utf-8")
	if err != nil {
		t.Fatal(err)
	}
	tests := []struct {
		column   columnDef
		value    any
		wantHex  string
		wantText string
		loss     bool
	}{
		{column: columnDef{Name: "N", DataType: "DECIMAL"}, value: dmNumber("123.45"), wantText: "123.45"},
		{column: columnDef{Name: "D", DataType: "DATE"}, value: "2026-07-11", wantHex: "EA0707000B00"},
		{column: columnDef{Name: "T", DataType: "TIME"}, value: "23:59:58.123456", wantHex: "17003B003A00", loss: true},
		{column: columnDef{Name: "TS", DataType: "TIMESTAMP"}, value: "2026-07-11 12:34:56.654321", wantHex: "EA0707000B000C002200380068250027"},
		{column: columnDef{Name: "TZ", DataType: "TIMESTAMP WITH TIME ZONE"}, value: "2026-07-11 12:34:56.654321 -04:30", wantText: "2026-07-11 12:34:56.654321 -04:30"},
		{column: columnDef{Name: "YM", DataType: "INTERVAL YEAR TO MONTH"}, value: "-1-02", wantText: "INTERVAL -'1-02' YEAR TO MONTH"},
		{column: columnDef{Name: "DS", DataType: "INTERVAL DAY TO SECOND"}, value: "3 04:05:06.123456", wantText: "INTERVAL '3 04:05:06.123456' DAY TO SECOND"},
		{column: columnDef{Name: "B", DataType: "VARBINARY"}, value: dmBinary{0x00, 0xFF, 0x10}, wantText: "00ff10"},
	}
	for _, test := range tests {
		field, loss, err := dmpFieldForDataColumn(test.column, test.value, charset)
		if err != nil {
			t.Fatalf("dmpFieldForDataColumn(%s) failed: %v", test.column.DataType, err)
		}
		if loss != test.loss {
			t.Fatalf("dmpFieldForDataColumn(%s) loss=%v want=%v", test.column.DataType, loss, test.loss)
		}
		if test.wantHex != "" && strings.ToUpper(hex.EncodeToString(field.Data)) != test.wantHex {
			t.Fatalf("dmpFieldForDataColumn(%s) hex=%s want=%s", test.column.DataType, strings.ToUpper(hex.EncodeToString(field.Data)), test.wantHex)
		}
		if test.wantText != "" && string(field.Data) != test.wantText {
			t.Fatalf("dmpFieldForDataColumn(%s) text=%q want=%q", test.column.DataType, field.Data, test.wantText)
		}
	}
}

func TestDetectDMPCaseSensitiveFromINI(t *testing.T) {
	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "dm.ini"), []byte("CASE_SENSITIVE = 0\n"), 0644); err != nil {
		t.Fatal(err)
	}
	value := detectDMPCaseSensitiveFromINI(filepath.Join(dir, "SYSTEM.DBF"), dir)
	if value == nil || *value {
		t.Fatalf("detected case_sensitive=%v, want false", value)
	}
}

func TestDetectDMPCaseSensitivePrefersSystemControlPage(t *testing.T) {
	dir := t.TempDir()
	const pageSize = uint32(8192)
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	raw := make([]byte, int(pageSize)*5)
	raw[int(pageSize)*systemControlPage4No+systemCaseSensitiveFlagOffset] = 0
	if err := os.WriteFile(systemPath, raw, 0644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "dm.ini"), []byte("CASE_SENSITIVE = 1\n"), 0644); err != nil {
		t.Fatal(err)
	}

	value := detectDMPCaseSensitive(systemPath, dir, pageSize)
	if value == nil || *value {
		t.Fatalf("detected case_sensitive=%v, want SYSTEM.DBF value false", value)
	}
}

func TestLOBPayloadReaderStreamsLongPageChain(t *testing.T) {
	const (
		pageSize    = 8192
		pageCount   = 300
		payloadSize = 32
		lobID       = 77
	)
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, pageSize*(pageCount+1))
	want := make([]byte, 0, pageCount*payloadSize)
	for i := 1; i <= pageCount; i++ {
		page := raw[i*pageSize : (i+1)*pageSize]
		putTestDMPageHeader(page, 4, 0, uint32(i), dmPageKindLOBData, 0)
		binary.LittleEndian.PutUint32(page[dmLOBPageIDOff:], lobID)
		binary.LittleEndian.PutUint16(page[dmLOBPagePayloadLenOff:], payloadSize)
		payload := bytes.Repeat([]byte{byte(i)}, payloadSize)
		copy(page[dmLOBPagePayloadOff:], payload)
		want = append(want, payload...)
		if i < pageCount {
			putTestDMPageRef(page, dmPageNextRefOff, 0, uint32(i+1))
		} else {
			putTestDMNullPageRef(page, dmPageNextRefOff)
		}
	}
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}
	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, pageSize)
	reader := &dmLOBReader{cache: cache}
	payloadReader, err := reader.openLOBPayload(dmLOBLocator{lobID: lobID, byteLen: uint32(len(want)), groupID: 4, firstPage: 1}, dmPageKindLOBData)
	if err != nil {
		t.Fatalf("openLOBPayload failed: %v", err)
	}
	got, err := io.ReadAll(payloadReader)
	if err != nil {
		t.Fatalf("ReadAll failed: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("streamed LOB mismatch: got=%d want=%d", len(got), len(want))
	}
	if len(cache.pages) > maxCachedDataFilePages {
		t.Fatalf("LOB page cache grew to %d pages, limit=%d", len(cache.pages), maxCachedDataFilePages)
	}
}

func TestRenderInsertResolvesLongRowLocator(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "MAIN.DBF")
	raw := make([]byte, 128*8192)
	page := raw[120*8192 : 121*8192]
	putTestDMPageHeader(page, 4, 0, 120, dmPageKindLongRowData, 0)
	putTestDMNullPageRef(page, dmPageNextRefOff)
	payload := []byte("LONG_ROW_PAYLOAD")
	recordOff := dmLOBPagePayloadOff
	recordLen := 0x0E + len(payload)
	binary.BigEndian.PutUint16(page[recordOff:], uint16(recordLen))
	binary.LittleEndian.PutUint32(page[recordOff+0x02:], 77)
	binary.LittleEndian.PutUint16(page[recordOff+0x0A:], uint16(len(payload)))
	binary.LittleEndian.PutUint16(page[recordOff+0x0C:], uint16(len(payload)))
	copy(page[recordOff+0x0E:], payload)
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}
	cache := newDataFilePageCache([]dataFileRef{{key: dataFileKey{groupID: 4, fileID: 0}, path: path}}, 8192)
	row := []byte{0x00, 0x1C, 0x04}
	var id [4]byte
	binary.LittleEndian.PutUint32(id[:], 1)
	row = append(row, id[:]...)
	row = append(row, makeTestLOBLocator(77, uint32(len(payload)), 4, 120)...)
	info := dataTableInfo{
		table:     dictionaryObject{Owner: "APP", Name: "T_LONG"},
		lobReader: &dmLOBReader{cache: cache},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"},
			{ColID: 2, Name: "V", DataType: "VARCHAR", Nullable: "Y"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if !strings.Contains(sql, "VALUES (1, 'LONG_ROW_PAYLOAD');") {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForRowBeforeTrailingColumnsWereAdded(t *testing.T) {
	row := []byte{
		0x00, 0x07, 0x00,
		0x0A, 0x00, 0x00, 0x00,
	}
	info := dataTableInfo{
		table:          dictionaryObject{Owner: "JYC", Name: "t"},
		historicalRows: true,
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
			{ColID: 2, Name: "name", DataType: "VARCHAR(20)", Nullable: "Y"},
			{ColID: 3, Name: "birth", DataType: "DATE", Nullable: "Y"},
		},
	}
	sql, start, end, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 3 || end != len(row) {
		t.Fatalf("unexpected data bounds: %d..%d", start, end)
	}
	want := `INSERT INTO JYC."t" ("id", "name", "birth") VALUES (10, NULL, NULL);`
	if !strings.Contains(sql, want) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertWithFixedCharOneBeforeDateTime(t *testing.T) {
	row := []byte{
		0x00, 0x3C, 0x00, 0x00,
		0xE9, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x0A, 0x00, 0x00, 0x00,
		0xE7, 0x87, 0x79,
		'Y',
		0xEA, 0x07, 0x2C, 0x2D, 0x9C, 0x01, 0x00, 0x00,
		0x86, 0xE5, 0xBC, 0xA0, 0xE4, 0xBC, 0x9F,
		0x94, 'z', 'h', 'a', 'n', 'g', 'w', 'e', 'i', '@', 'e', 'x', 'a', 'm', 'p', 'l', 'e', '.', 'c', 'o', 'm',
		0x83, 0xC3, 0x02, 0x56,
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "DMTEST", Name: "T_EMPLOYEE"},
		columns: []columnDef{
			{ColID: 0, Name: "EMP_ID", DataType: "BIGINT", Length: 8, Nullable: "N"},
			{ColID: 1, Name: "DEPT_ID", DataType: "INT", Length: 4, Nullable: "N"},
			{ColID: 2, Name: "EMP_NAME", DataType: "VARCHAR", Length: 100, Nullable: "N"},
			{ColID: 3, Name: "EMAIL", DataType: "VARCHAR", Length: 128, Nullable: "Y"},
			{ColID: 4, Name: "SALARY", DataType: "DECIMAL", Length: 12, Scale: 2, Nullable: "N"},
			{ColID: 5, Name: "HIRE_DATE", DataType: "DATE", Length: 3, Nullable: "N"},
			{ColID: 6, Name: "ACTIVE_FLAG", DataType: "CHAR", Length: 1, Nullable: "N"},
			{ColID: 7, Name: "CREATED_AT", DataType: "DATETIME", Length: 8, Scale: 6, Nullable: "N"},
		},
	}
	sql, start, end, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 4 || end != len(row) {
		t.Fatalf("unexpected data bounds: %d..%d", start, end)
	}
	want := "VALUES (1001, 10, '张伟', 'zhangwei@example.com', 18500, DATE '2023-03-15', 'Y', DATETIME '2026-08-05 13:33:51.000000');"
	if !strings.Contains(sql, want) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForRowBeforeTrailingFixedColumnWasAdded(t *testing.T) {
	row := []byte{
		0x00, 0x0B, 0x00,
		0x0A, 0x00, 0x00, 0x00,
		0x83, 'j', 'i', 'e',
	}
	info := dataTableInfo{
		table:          dictionaryObject{Owner: "JYC", Name: "t"},
		historicalRows: true,
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
			{ColID: 2, Name: "name", DataType: "VARCHAR(20)", Nullable: "Y"},
			{ColID: 3, Name: "birth", DataType: "DATE", Nullable: "Y"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	want := `INSERT INTO JYC."t" ("id", "name", "birth") VALUES (10, 'jie', NULL);`
	if !strings.Contains(sql, want) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForIndexLikeRowDoesNotUseHistoricalColumnFallback(t *testing.T) {
	row := []byte{
		0x00, 0x07, 0x00,
		0x01, 0x00, 0x00, 0x00,
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "JYC", Name: "t"},
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
			{ColID: 2, Name: "name", DataType: "VARCHAR(20)", Nullable: "Y"},
			{ColID: 3, Name: "birth", DataType: "DATE", Nullable: "Y"},
		},
	}
	if _, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"}); err == nil {
		t.Fatal("index-like single-key row should not be decoded via historical column fallback")
	}
}

func TestSelectDataPageCandidateSkipsLooseHistoricalRowLeaf(t *testing.T) {
	row := []byte{
		0x00, 0x07, 0x00,
		0x0A, 0x00, 0x00, 0x00,
	}
	page := make([]byte, 8192)
	putTestDMPageHeader(page, 4, 0, 336, dmPageKindRowData, 33555517)
	copy(page[dataRowAreaStart:], row)
	candidate := dataTableInfo{
		table:          dictionaryObject{Owner: "JYC", Name: "t", ID: 1069},
		historicalRows: true,
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
			{ColID: 2, Name: "name", DataType: "VARCHAR(20)", Nullable: "Y"},
			{ColID: 3, Name: "birth", DataType: "DATE", Nullable: "Y"},
		},
	}
	_, ok := selectDataPageCandidate(
		[]dataTableInfo{candidate},
		dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}},
		336,
		page,
		8192,
		[]locatedDataRow{{slotNo: 1, offset: dataRowAreaStart, length: uint16(len(row))}},
		textDecoder{preferred: "utf-8"},
	)
	if ok {
		t.Fatal("loose historical candidate should not be selected on ordinary row/index leaf page")
	}

	candidate.recoveryMode = true
	putTestDMPageHeader(page, 4, 0, 592, dmPageKindRowOverflow, 33555536)
	_, ok = selectDataPageCandidate(
		[]dataTableInfo{candidate},
		dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}},
		592,
		page,
		8192,
		[]locatedDataRow{{slotNo: 1, offset: dataRowAreaStart, length: uint16(len(row))}},
		textDecoder{preferred: "utf-8"},
	)
	if !ok {
		t.Fatal("row overflow/residual page should be selectable in explicit recovery mode")
	}
}

func TestSelectDataPageCandidateSkipsTableAssistHeaderWhenStorageIsKnown(t *testing.T) {
	row := []byte{
		0x00, 0x0A,
		0x3C,
		0x0A, 0x00, 0x00, 0x00,
		0x00, 0x00, 0x01,
	}
	page := make([]byte, 8192)
	tableID := uint32(1069)
	candidate := dataTableInfo{
		table:          dictionaryObject{Owner: "JYC", Name: "t", ID: tableID},
		dataStorageID:  33555535,
		historicalRows: true,
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
			{ColID: 2, Name: "name", DataType: "VARCHAR(20)", Nullable: "Y"},
			{ColID: 3, Name: "birth", DataType: "DATE", Nullable: "Y"},
		},
	}
	putTestDMPageHeader(page, 4, 0, 576, dmPageKindRowData, tableDataAssistID(tableID))
	copy(page[dataRowAreaStart:], row)
	_, ok := selectDataPageCandidate(
		[]dataTableInfo{candidate},
		dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}},
		576,
		page,
		8192,
		[]locatedDataRow{{slotNo: 1, offset: dataRowAreaStart, length: uint16(len(row))}},
		textDecoder{preferred: "utf-8"},
	)
	if ok {
		t.Fatal("tableDataAssist row page should be skipped when dictionary already knows the real data storage")
	}

	candidate.recoveryMode = true
	putTestDMPageHeader(page, 4, 0, 592, dmPageKindRowOverflow, 33555536)
	_, ok = selectDataPageCandidate(
		[]dataTableInfo{candidate},
		dataFileRef{key: dataFileKey{groupID: 4, fileID: 0}},
		592,
		page,
		8192,
		[]locatedDataRow{{slotNo: 1, offset: dataRowAreaStart, length: uint16(len(row))}},
		textDecoder{preferred: "utf-8"},
	)
	if !ok {
		t.Fatal("row overflow/residual page should be selectable in explicit recovery mode")
	}
}

func TestRenderInsertForTrailingNullVariableRow(t *testing.T) {
	row := make([]byte, 141)
	row[0] = 0x00
	binary.LittleEndian.PutUint16(row[1:], uint16(len(row)))
	row[5] = 0x3F
	row[6] = 0xC0
	putInt32 := func(pos int, value int32) {
		binary.LittleEndian.PutUint32(row[pos:], uint32(value))
	}
	putInt64 := func(pos int, value int64) {
		binary.LittleEndian.PutUint64(row[pos:], uint64(value))
	}
	putInt32(7, 1038)
	putInt32(11, 5)
	putInt32(15, 0)
	putInt32(19, 16)
	putInt32(23, 1)
	putInt32(27, 3)
	putInt32(31, 1)
	putInt32(35, 98)
	putInt32(39, 56)
	putInt32(43, 0)
	putInt64(47, 118250)
	putInt64(55, 1)
	pos := 75
	for _, value := range []string{"SYSDBA", "BIN_TEST2", "TBS_BIN_TEST", "SYSDBA.BIN_TEST2"} {
		row[pos] = byte(0x80 + len(value))
		pos++
		copy(row[pos:], value)
		pos += len(value)
	}
	copy(row[pos:], []byte{0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF})

	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "DM_DATA_ROW_SCAN"},
		columns: []columnDef{
			{ColID: 1, Name: "owner", DataType: "varchar", Nullable: "Y"},
			{ColID: 2, Name: "table_name", DataType: "varchar", Nullable: "Y"},
			{ColID: 3, Name: "table_id", DataType: "INT", Nullable: "Y"},
			{ColID: 4, Name: "tablespace_name", DataType: "varchar", Nullable: "Y"},
			{ColID: 5, Name: "ts_id", DataType: "INT", Nullable: "Y"},
			{ColID: 6, Name: "file_id", DataType: "INT", Nullable: "Y"},
			{ColID: 7, Name: "page_no", DataType: "INT", Nullable: "Y"},
			{ColID: 8, Name: "slot_no", DataType: "INT", Nullable: "Y"},
			{ColID: 9, Name: "n_slot", DataType: "INT", Nullable: "Y"},
			{ColID: 10, Name: "n_rec", DataType: "INT", Nullable: "Y"},
			{ColID: 11, Name: "row_offset", DataType: "INT", Nullable: "Y"},
			{ColID: 12, Name: "row_len", DataType: "INT", Nullable: "Y"},
			{ColID: 13, Name: "is_del", DataType: "INT", Nullable: "Y"},
			{ColID: 14, Name: "trx_id", DataType: "bigint", Nullable: "Y"},
			{ColID: 15, Name: "clu_rowid", DataType: "bigint", Nullable: "Y"},
			{ColID: 16, Name: "roll_addr_file", DataType: "INT", Nullable: "Y"},
			{ColID: 17, Name: "roll_addr_page", DataType: "INT", Nullable: "Y"},
			{ColID: 18, Name: "roll_addr_off", DataType: "INT", Nullable: "Y"},
			{ColID: 19, Name: "page_tname", DataType: "varchar", Nullable: "Y"},
			{ColID: 20, Name: "datafile_path", DataType: "varchar", Nullable: "Y"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	want := "VALUES ('SYSDBA', 'BIN_TEST2', 1038, 'TBS_BIN_TEST', 5, 0, 16, 1, 3, 1, 98, 56, 0, 118250, 1, NULL, NULL, NULL, 'SYSDBA.BIN_TEST2', NULL);"
	if !strings.Contains(sql, want) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestReadExtendedDataVarchar(t *testing.T) {
	raw := append([]byte{0xC2}, []byte(strings.Repeat("A", 66))...)
	got, next, err := readShortDataVarchar(raw, 0, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("readShortDataVarchar returned error: %v", err)
	}
	if got != strings.Repeat("A", 66) {
		t.Fatalf("readShortDataVarchar = %q", got)
	}
	if next != len(raw) {
		t.Fatalf("next = %d, want %d", next, len(raw))
	}
}

func TestReadTwoByteLengthDataVarchar(t *testing.T) {
	raw := append([]byte{0x01, 0x04}, []byte(strings.Repeat("A", 260))...)
	got, next, err := readShortDataVarchar(raw, 0, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("readShortDataVarchar returned error: %v", err)
	}
	if got != strings.Repeat("A", 260) {
		t.Fatalf("readShortDataVarchar len = %d, want 260", len(got))
	}
	if next != len(raw) {
		t.Fatalf("next = %d, want %d", next, len(raw))
	}
}

func TestReadShortDataBytes(t *testing.T) {
	raw := append([]byte{0x8E}, []byte("Hello DaMeng 1")...)
	got, next, err := readShortDataBytes(raw, 0)
	if err != nil {
		t.Fatalf("readShortDataBytes returned error: %v", err)
	}
	if string(got) != "Hello DaMeng 1" {
		t.Fatalf("readShortDataBytes = %q", string(got))
	}
	if next != len(raw) {
		t.Fatalf("next = %d, want %d", next, len(raw))
	}
}

func TestRenderInsertForInlineLOBRow(t *testing.T) {
	row := make([]byte, 0, 128)
	row = append(row, 0x00, 0x00, 0x00)
	var id [4]byte
	binary.LittleEndian.PutUint32(id[:], 1)
	row = append(row, id[:]...)
	var dt [8]byte
	v := uint64(2026) |
		uint64(6)<<15 |
		uint64(26)<<19 |
		uint64(9)<<24 |
		uint64(46)<<29 |
		uint64(2)<<35
	binary.LittleEndian.PutUint64(dt[:], v)
	row = append(row, dt[:]...)
	row = append(row, 0x8C)
	row = append(row, []byte("LOB_TEST_001")...)
	clobText := "这是CLOB测试"
	clobBytes := testInlineLOBEnvelope(1, []byte(clobText))
	row = append(row, byte(0x80+len(clobBytes)))
	row = append(row, clobBytes...)
	blobData := []byte("Hello DaMeng 1")
	blobBytes := testInlineLOBEnvelope(2, blobData)
	row = append(row, byte(0x80+len(blobBytes)))
	row = append(row, blobBytes...)
	binary.BigEndian.PutUint16(row[0:], uint16(len(row)))

	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "T_LOB_TEST"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"},
			{ColID: 2, Name: "BIZ_NO", DataType: "VARCHAR2", Nullable: "Y"},
			{ColID: 3, Name: "CLOB_TEXT", DataType: "CLOB", Nullable: "Y"},
			{ColID: 4, Name: "BLOB_DATA", DataType: "BLOB", Nullable: "Y"},
			{ColID: 5, Name: "CREATE_TIME", DataType: "DATETIME", Nullable: "Y"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if !strings.Contains(sql, "CLOB_TEXT, BLOB_DATA") || !strings.Contains(sql, "'这是CLOB测试'") {
		t.Fatalf("unexpected CLOB insert sql: %s", sql)
	}
	if !strings.Contains(sql, "HEXTORAW('48656C6C6F2044614D656E672031')") {
		t.Fatalf("unexpected BLOB insert sql: %s", sql)
	}
}

func TestRenderInsertForAllInlineLOBTypes(t *testing.T) {
	raw, err := hex.DecodeString("00AE0000010000009301560401000000000006000000544558543F3F93015604020000000000060000004C4F4E473F3F9A0156040300000000000D0000004C4F4E47564152434841523F3F92015604040000000000050000000102030405920156040500000000000500000010203040509301560406000000000006000000FFEEDDCCBBAA9501560407000000000008000000434C4F423F3F3F3F010000000000FFFFFFFF7FFFFFA31002000000")
	if err != nil {
		t.Fatal(err)
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "DMDUL_T_LOB"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "INT", Nullable: "N"},
			{ColID: 2, Name: "C_TEXT", DataType: "TEXT", Nullable: "Y"},
			{ColID: 3, Name: "C_LONG", DataType: "CLOB", Nullable: "Y"},
			{ColID: 4, Name: "C_LONGVARCHAR", DataType: "LONGVARCHAR", Nullable: "Y"},
			{ColID: 5, Name: "C_IMAGE", DataType: "IMAGE", Nullable: "Y"},
			{ColID: 6, Name: "C_LONGVARBINARY", DataType: "LONGVARBINARY", Nullable: "Y"},
			{ColID: 7, Name: "C_BLOB", DataType: "BLOB", Nullable: "Y"},
			{ColID: 8, Name: "C_CLOB", DataType: "CLOB", Nullable: "Y"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, raw, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	for _, want := range []string{"'TEXT??'", "'LONG??'", "'LONGVARCHAR??'", "HEXTORAW('0102030405')", "HEXTORAW('1020304050')", "HEXTORAW('FFEEDDCCBBAA')", "'CLOB????'"} {
		if !strings.Contains(sql, want) {
			t.Fatalf("insert SQL does not contain %s: %s", want, sql)
		}
	}
}

func testInlineLOBEnvelope(seq byte, payload []byte) []byte {
	raw := make([]byte, 13+len(payload))
	raw[0] = 0x01
	raw[1] = 0x27
	raw[2] = 0x04
	raw[3] = seq
	binary.LittleEndian.PutUint32(raw[9:13], uint32(len(payload)))
	copy(raw[13:], payload)
	return raw
}

func makeTestLOBLocator(lobID uint32, byteLen uint32, groupID uint32, firstPage uint32) []byte {
	raw := make([]byte, dmLOBLocatorSize)
	raw[0] = 0x02
	binary.LittleEndian.PutUint32(raw[1:5], lobID)
	binary.LittleEndian.PutUint32(raw[9:13], byteLen)
	binary.LittleEndian.PutUint32(raw[13:17], groupID)
	binary.LittleEndian.PutUint32(raw[17:21], firstPage)
	return raw
}

func TestRenderInsertForHeapRowWithLongVarchar(t *testing.T) {
	text := strings.Repeat("堆表测试数据-第1条", 10)
	row := make([]byte, 0, 0x126)
	row = append(row, 0x01, 0x26, 0x00)
	var id [8]byte
	binary.LittleEndian.PutUint64(id[:], 1)
	row = append(row, id[:]...)
	var dt [8]byte
	v := uint64(2026) |
		uint64(6)<<15 |
		uint64(24)<<19 |
		uint64(13)<<24 |
		uint64(7)<<29 |
		uint64(28)<<35
	binary.LittleEndian.PutUint64(dt[:], v)
	row = append(row, dt[:]...)
	rawText := []byte(text)
	row = append(row, byte(len(rawText)>>8), byte(len(rawText)))
	row = append(row, rawText...)
	row = append(row, []byte{0xFF, 0xFF, 0xFF, 0xFF, 0x7F, 0xFF, 0xFF, 0x87, 0xDD, 0x01, 0x00, 0x00, 0x00}...)

	info := dataTableInfo{
		table: dictionaryObject{Owner: "HR_TEST", Name: "T_LOG_HEAP"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "BIGINT"},
			{ColID: 2, Name: "LOG_TIME", DataType: "DATETIME"},
			{ColID: 3, Name: "LOG_TEXT", DataType: "VARCHAR2"},
		},
	}
	sql, _, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if !strings.Contains(sql, "VALUES (1, DATETIME '2026-06-24 13:07:28.000000'") || !strings.Contains(sql, text) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForIOTRowWithNullableFixedSentinel(t *testing.T) {
	row := []byte{
		0x00, 0x8D, 0x00, 0x03, 0x00,
		0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x32, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
		0x01,
		0xEA, 0x07, 0xD3, 0xEA, 0xCE, 0x72, 0x4B, 0x0A,
		0x00, 0x00, 0x3B, 0x02, 0x00, 0x00, 0x73, 0x7F,
		0x86, 'u', 's', 'e', 'r', '_', '1',
		0xA0, 'e', '1', '0', 'a', 'd', 'c', '3', '9', '4', '9', 'b', 'a', '5', '9', 'a', 'b', 'b', 'e', '5', '6', 'e', '0', '5', '7', 'f', '2', '0', 'f', '8', '8', '3', 'e',
		0x89, 0xB2, 0xE2, 0xCA, 0xD4, 0xD3, 0xC3, 0xBB, 0xA7, 0x31,
		0x8B, '1', '3', '8', '6', '.', '0', '5', '7', '1', '3', '6',
		0x8B, 'u', '1', '@', 't', 'e', 's', 't', '.', 'c', 'o', 'm',
		0x89, 0xB2, 0xE2, 0xCA, 0xD4, 0xCA, 0xFD, 0xBE, 0xDD, 0x31,
		0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF,
		0xFF, 0xFF, 0x7F, 0xFF, 0xFF, 0x50, 0x09, 0x04, 0x00, 0x00, 0x00,
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "SYS_USER"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "BIGINT", Nullable: "N"},
			{ColID: 2, Name: "USERNAME", DataType: "VARCHAR", Nullable: "N"},
			{ColID: 3, Name: "PASSWORD", DataType: "VARCHAR", Nullable: "N"},
			{ColID: 4, Name: "REAL_NAME", DataType: "VARCHAR", Nullable: "Y"},
			{ColID: 5, Name: "PHONE", DataType: "VARCHAR", Nullable: "Y"},
			{ColID: 6, Name: "EMAIL", DataType: "VARCHAR", Nullable: "Y"},
			{ColID: 7, Name: "DEPT_ID", DataType: "BIGINT", Nullable: "Y"},
			{ColID: 8, Name: "STATUS", DataType: "TINYINT", Nullable: "Y"},
			{ColID: 9, Name: "CREATE_TIME", DataType: "DATETIME", Nullable: "Y"},
			{ColID: 10, Name: "UPDATE_TIME", DataType: "DATETIME", Nullable: "Y"},
			{ColID: 11, Name: "REMARK", DataType: "VARCHAR", Nullable: "Y"},
		},
	}
	sql, start, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "gb18030"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 5 {
		t.Fatalf("data start = %d, want 5", start)
	}
	for _, want := range []string{
		"SYSDBA.SYS_USER",
		"VALUES (1, 'user_1'",
		"DATETIME '2026-06-26 10:55:25.337337'",
		"NULL, '测试数据1'",
	} {
		if !strings.Contains(sql, want) {
			t.Fatalf("insert sql missing %q: %s", want, sql)
		}
	}
}

func TestRenderInsertForSingleFixedColumnPrefersRowHeaderStart(t *testing.T) {
	row := []byte{
		0x00, 0x1A, 0x00,
		0x14, 0x00, 0x00, 0x00,
		0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
		0xFF, 0xFF, 0xFF, 0xFF, 0x7F, 0xFF, 0xFF,
		0xE2, 0x19, 0x01, 0x00, 0x00, 0x00,
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "SY", Name: "t"},
		columns: []columnDef{
			{ColID: 1, Name: "id", DataType: "INT", Nullable: "Y"},
		},
	}
	sql, start, _, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 3 {
		t.Fatalf("data start = %d, want 3", start)
	}
	if !strings.Contains(sql, `INSERT INTO SY."t" ("id") VALUES (20);`) {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestRenderInsertForDataRow(t *testing.T) {
	row := []byte{
		0x00, 0x0E, 0x00,
		0x64, 0x00, 0x00, 0x00,
		0x83, 'A', 'B', 'C',
	}
	info := dataTableInfo{
		table: dictionaryObject{Owner: "SYSDBA", Name: "T1"},
		columns: []columnDef{
			{ColID: 1, Name: "ID", DataType: "INT"},
			{ColID: 2, Name: "NAME", DataType: "VARCHAR"},
		},
	}
	sql, start, end, err := renderInsertForDataRow(info, row, textDecoder{preferred: "utf-8"})
	if err != nil {
		t.Fatalf("renderInsertForDataRow returned error: %v", err)
	}
	if start != 3 || end != len(row) {
		t.Fatalf("unexpected data bounds: %d..%d", start, end)
	}
	if !strings.Contains(sql, "INSERT INTO SYSDBA.T1 (ID, NAME) VALUES (100, 'ABC');") {
		t.Fatalf("unexpected insert sql: %s", sql)
	}
}

func TestTableNameMatcherPrefersQualifiedNames(t *testing.T) {
	matcher := newTableNameMatcher(`SYSDBA.BIN_TEST2,"SYSDBA"."中文测试表"`)
	if !matcher.allowed("SYSDBA", "BIN_TEST2") {
		t.Fatal("expected qualified ASCII table to match")
	}
	if !matcher.allowed("SYSDBA", "中文测试表") {
		t.Fatal("expected quoted qualified Chinese table to match")
	}
	if matcher.allowed("OTHER", "BIN_TEST2") {
		t.Fatal("qualified filter should not match same table name in another owner")
	}
}

func TestTableNameMatcherAllDefaultBehavior(t *testing.T) {
	if !newTableNameMatcher("all").allowed("SYSDBA", "BIN_TEST2") {
		t.Fatal("all table filter should allow any table")
	}
	if newTableNameMatcher("").allowed("SYSDBA", "BIN_TEST2") {
		t.Fatal("empty matcher should not allow tables by itself")
	}
}

func writeDataExportTestSystem(t *testing.T, path string) {
	t.Helper()
	raw := make([]byte, 5*8192)
	binary.LittleEndian.PutUint32(raw[0x80:], 16)
	binary.LittleEndian.PutUint32(raw[0x84:], 8192)
	binary.LittleEndian.PutUint32(raw[0x8C:], 5)
	raw[4*8192+0x2D] = 1
	if err := os.WriteFile(path, raw, 0644); err != nil {
		t.Fatal(err)
	}
}

func testDataExportDictionary(systemPath string, storageID uint32, rootPage uint32, headerPage uint32, blocks uint32) *DictionaryInfo {
	return &DictionaryInfo{
		SystemPath: systemPath,
		PageSize:   8192,
		Users:      []DictionaryUser{{ID: 10, Name: "APP"}},
		Tables: []DictionaryTable{{
			ID: 1001, Owner: "APP", Name: "T_PLAN", ColumnCount: 1,
			Tablespace: "MAIN", GroupID: 4, Storage: "CLUSTERBTR",
			StorageID: storageID, RootFile: 0, RootPage: rootPage,
			HeaderFile: 0, HeaderBlock: headerPage, Blocks: blocks, Extents: 1,
		}},
		Columns: []DictionaryColumn{{
			TableID: 1001, TableOwner: "APP", TableName: "T_PLAN",
			ColID: 1, Name: "ID", DataType: "INT", Nullable: "N",
		}},
	}
}

func putTestIntDataPage(page []byte, groupID uint16, fileID uint16, pageNo uint32, storageID uint32, value int32) {
	putTestDMPageHeader(page, groupID, fileID, pageNo, dmPageKindRowData, storageID)
	binary.LittleEndian.PutUint16(page[dataPageSlotCountOff:], 1)
	binary.LittleEndian.PutUint16(page[dataPageFreeEndOff:], dataRowAreaStart+7)
	binary.LittleEndian.PutUint16(page[dataPageRecordCountOff:], 1)
	binary.LittleEndian.PutUint16(page[dataPageTreeLevelOff:], 0)
	binary.BigEndian.PutUint16(page[dataRowAreaStart:], 7)
	page[dataRowAreaStart+2] = 0
	binary.LittleEndian.PutUint32(page[dataRowAreaStart+3:], uint32(value))
	putTestDataPageSlot(page, len(page), 1, 1, dataRowAreaStart)
}

func readDataExportTestFile(t *testing.T, path string) string {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(raw)
}

func putTestRow(page []byte, pos int, length int, flag byte) {
	binary.BigEndian.PutUint16(page[pos:], uint16(length))
	page[pos+2] = flag
}

func putTestDataPageSlot(page []byte, pageSize int, slotCount int, slotNo int, rowOff int) {
	slotArrayStart := pageSize - pageSlotTrailerLen - slotCount*2
	binary.LittleEndian.PutUint16(page[slotArrayStart+(slotNo-1)*2:], uint16(rowOff))
}

func putTestDMPageHeader(page []byte, groupID uint16, fileID uint16, pageNo uint32, kind uint32, storageID uint32) {
	binary.LittleEndian.PutUint16(page[0:], groupID)
	binary.LittleEndian.PutUint16(page[2:], fileID)
	binary.LittleEndian.PutUint32(page[4:], pageNo)
	binary.LittleEndian.PutUint32(page[dmPageKindOff:], kind)
	binary.LittleEndian.PutUint32(page[dataPageAssistIndexOff:], storageID)
}

func putTestDMPageRef(page []byte, offset int, fileID uint16, pageNo uint32) {
	binary.LittleEndian.PutUint16(page[offset:], fileID)
	binary.LittleEndian.PutUint32(page[offset+2:], pageNo)
}

func putTestDMNullPageRef(page []byte, offset int) {
	for i := 0; i < 6; i++ {
		page[offset+i] = 0xFF
	}
}

func TestWriteRowCountsOversizedSQLStatements(t *testing.T) {
	dir := t.TempDir()
	table := dataTableInfo{table: dictionaryObject{ID: 77, Owner: "APP", Name: "T_LOB"}}
	router, err := newDataOutputRouter(DataExportOptions{OutputPath: filepath.Join(dir, "out.sql")}, "sql", map[uint32]dataTableInfo{77: table})
	if err != nil {
		t.Fatalf("newDataOutputRouter failed: %v", err)
	}
	defer router.close()
	small := "INSERT INTO APP.T_LOB VALUES (1, 'x');"
	big := "INSERT INTO APP.T_LOB VALUES (2, '" + strings.Repeat("a", disqlMaxStatementBytes) + "');"
	if err := router.writeRow(table, small, nil); err != nil {
		t.Fatalf("writeRow(small) failed: %v", err)
	}
	if err := router.writeRow(table, big, nil); err != nil {
		t.Fatalf("writeRow(big) failed: %v", err)
	}
	if router.oversizedSQLRows != 1 {
		t.Fatalf("oversizedSQLRows = %d, want 1", router.oversizedSQLRows)
	}
	tables := sortedOversizedSQLTables(router.oversizedSQLTableIDs)
	if len(tables) != 1 || tables[0] != "APP.T_LOB" {
		t.Fatalf("oversized tables = %v, want [APP.T_LOB]", tables)
	}
}

func TestRowCoverageKeysSkippedForPlainDirectReadRows(t *testing.T) {
	columns := []columnDef{
		{ColID: 0, Name: "ID", DataType: "INT"},
		{ColID: 1, Name: "V", DataType: "VARCHAR"},
	}
	values := map[uint16]dataValue{
		0: {value: int32(1)},
		1: {value: "x"},
	}
	full := dataRowRenderMetaForValues(columns, values, false)
	if full.partial || len(full.coverageKeys) != 0 || full.prefixKey != "" {
		t.Fatalf("untracked full row must carry no coverage keys: %+v", full)
	}
	tracked := dataRowRenderMetaForValues(columns, values, true)
	if len(tracked.coverageKeys) != 2 || tracked.prefixKey == "" {
		t.Fatalf("tracked full row must carry coverage keys: %+v", tracked)
	}
	partialValues := map[uint16]dataValue{0: {value: int32(1)}}
	partial := dataRowRenderMetaForValues(columns, partialValues, false)
	if !partial.partial || len(partial.coverageKeys) != 1 || partial.prefixKey == "" {
		t.Fatalf("partial row must carry its own coverage keys even untracked: %+v", partial)
	}
}

func TestStampRowCoverageTrackingMarksHistoricalTables(t *testing.T) {
	plain := dataTableInfo{table: dictionaryObject{ID: 1, Owner: "A", Name: "PLAIN"}}
	histPrimary := dataTableInfo{table: dictionaryObject{ID: 2, Owner: "A", Name: "HIST"}}
	histAssist := histPrimary
	histAssist.historicalRows = true
	assistByID := map[uint32][]dataTableInfo{
		100: {plain},
		200: {histPrimary},
		201: {histAssist},
	}
	units := map[uint32]dataTableInfo{1: plain, 2: histPrimary}
	states := stampRowCoverageTracking(assistByID, units, false)
	if assistByID[100][0].coverage != nil || states[1] != nil {
		t.Fatalf("plain table must not track coverage")
	}
	if assistByID[200][0].coverage == nil || assistByID[201][0].coverage == nil {
		t.Fatalf("historical table candidates must all track coverage")
	}
	if assistByID[200][0].coverage != assistByID[201][0].coverage {
		t.Fatalf("historical table candidates must share one coverage state")
	}
	if units[2].coverage == nil || units[1].coverage != nil {
		t.Fatalf("storage units must mirror table coverage: %+v", units)
	}
	states = stampRowCoverageTracking(assistByID, units, true)
	if assistByID[100][0].coverage == nil || states[1] == nil {
		t.Fatalf("recovery mode must track coverage for every table")
	}
}

func TestTableCoverageStateOverflowStopsTracking(t *testing.T) {
	state := &tableCoverageState{keys: make(map[string]bool, maxCoverageKeysPerTable)}
	for i := 0; len(state.keys) < maxCoverageKeysPerTable-1; i++ {
		state.keys[fmt.Sprintf("k%d", i)] = true
	}
	state.mark([]string{"final-key"})
	if !state.overflow.Load() || state.keys != nil {
		t.Fatalf("state must overflow and drop keys at the cap: overflow=%v keysNil=%v", state.overflow.Load(), state.keys == nil)
	}
	if state.active() {
		t.Fatalf("overflowed state must not stay active")
	}
	state.mark([]string{"later"})
	if state.covered("later") || state.covered("final-key") {
		t.Fatalf("overflowed state must not report coverage")
	}
}

func TestParallelDirectUnloadMatchesSequentialOutput(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555438
	const pageCount = 600
	raw := make([]byte, (16+pageCount)*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	for i := 0; i < pageCount; i++ {
		pageNo := uint32(16 + i)
		page := raw[int(pageNo)*8192 : (int(pageNo)+1)*8192]
		putTestIntDataPage(page, 4, 0, pageNo, storageID, int32(1000+i))
		if i < pageCount-1 {
			putTestDMPageRef(page, dmPageNextRefOff, 0, pageNo+1)
		} else {
			putTestDMNullPageRef(page, dmPageNextRefOff)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 16, 0, 0)
	run := func(workers string, out string) (*DataExportResult, string) {
		t.Setenv("DMDUL_UNLOAD_WORKERS", workers)
		result, err := ExportData(DataExportOptions{
			SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, out),
			OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", Dictionary: dict,
		})
		if err != nil {
			t.Fatalf("ExportData(workers=%s) failed: %v", workers, err)
		}
		return result, readDataExportTestFile(t, filepath.Join(dir, out))
	}
	seqResult, seqSQL := run("1", "seq.sql")
	parResult, parSQL := run("4", "par.sql")
	if seqResult.DirectPagesRead != pageCount || seqResult.RowsExported != pageCount {
		t.Fatalf("sequential run did not direct-read the full plan: %+v", seqResult)
	}
	if parResult.DirectPagesRead != seqResult.DirectPagesRead ||
		parResult.RowsExported != seqResult.RowsExported ||
		parResult.RowsFailed != seqResult.RowsFailed ||
		parResult.PagesScanned != seqResult.PagesScanned ||
		parResult.FallbackPagesScanned != seqResult.FallbackPagesScanned {
		t.Fatalf("parallel counters diverge: seq=%+v par=%+v", seqResult, parResult)
	}
	if seqSQL != parSQL {
		t.Fatalf("parallel output is not byte-identical to sequential output (len %d vs %d)", len(seqSQL), len(parSQL))
	}
	if !strings.Contains(parSQL, "VALUES (1000)") || !strings.Contains(parSQL, fmt.Sprintf("VALUES (%d)", 1000+pageCount-1)) {
		t.Fatalf("parallel output is missing boundary rows")
	}
}

func TestParallelDirectUnloadDMPMatchesSequentialOutput(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555439
	const pageCount = 600
	raw := make([]byte, (16+pageCount)*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	for i := 0; i < pageCount; i++ {
		pageNo := uint32(16 + i)
		page := raw[int(pageNo)*8192 : (int(pageNo)+1)*8192]
		putTestIntDataPage(page, 4, 0, pageNo, storageID, int32(2000+i))
		if i < pageCount-1 {
			putTestDMPageRef(page, dmPageNextRefOff, 0, pageNo+1)
		} else {
			putTestDMNullPageRef(page, dmPageNextRefOff)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 16, 0, 0)
	run := func(workers string, out string) []byte {
		t.Setenv("DMDUL_UNLOAD_WORKERS", workers)
		result, err := ExportData(DataExportOptions{
			SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, out),
			OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8",
			OutputFormat: "dmp", Dictionary: dict,
		})
		if err != nil {
			t.Fatalf("ExportData(dmp workers=%s) failed: %v", workers, err)
		}
		if result.RowsExported != pageCount || result.RowsFailed != 0 {
			t.Fatalf("dmp export rows are wrong (workers=%s): %+v", workers, result)
		}
		data, err := os.ReadFile(filepath.Join(dir, out))
		if err != nil {
			t.Fatal(err)
		}
		return data
	}
	seq := run("1", "seq.dmp")
	par := run("4", "par.dmp")
	if !bytes.Equal(seq, par) {
		t.Fatalf("parallel dmp output is not byte-identical (len %d vs %d)", len(seq), len(par))
	}
	info, err := InspectDMP(filepath.Join(dir, "par.dmp"))
	if err != nil || !info.PayloadMD5Valid || len(info.Tables) != 1 || info.Tables[0].RowCount != pageCount {
		t.Fatalf("parallel dmp failed inspection: err=%v info=%+v", err, info)
	}
}

func TestParallelDirectUnloadBackpressureStaysDeterministic(t *testing.T) {
	dir := t.TempDir()
	systemPath := filepath.Join(dir, "SYSTEM.DBF")
	writeDataExportTestSystem(t, systemPath)
	const storageID = 33555441
	const pageCount = 900
	raw := make([]byte, (16+pageCount)*8192)
	putTestDMPageHeader(raw[:8192], 4, 0, 0, 0, 0)
	for i := 0; i < pageCount; i++ {
		pageNo := uint32(16 + i)
		page := raw[int(pageNo)*8192 : (int(pageNo)+1)*8192]
		putTestIntDataPage(page, 4, 0, pageNo, storageID, int32(3000+i))
		if i < pageCount-1 {
			putTestDMPageRef(page, dmPageNextRefOff, 0, pageNo+1)
		} else {
			putTestDMNullPageRef(page, dmPageNextRefOff)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "MAIN.DBF"), raw, 0644); err != nil {
		t.Fatal(err)
	}
	dict := testDataExportDictionary(systemPath, storageID, 16, 0, 0)
	run := func(name string, envs map[string]string) []byte {
		for k, v := range envs {
			t.Setenv(k, v)
		}
		result, err := ExportData(DataExportOptions{
			SystemPath: systemPath, DataDir: dir, OutputPath: filepath.Join(dir, name),
			OwnerFilter: "APP", TableFilter: "APP.T_PLAN", Charset: "utf-8", Dictionary: dict,
		})
		if err != nil {
			t.Fatalf("ExportData(%s) failed: %v", name, err)
		}
		if result.RowsExported != pageCount || result.DirectPagesRead != pageCount {
			t.Fatalf("%s exported wrong counts: %+v", name, result)
		}
		data, err := os.ReadFile(filepath.Join(dir, name))
		if err != nil {
			t.Fatal(err)
		}
		return data
	}
	seq := run("seq.sql", map[string]string{"DMDUL_UNLOAD_WORKERS": "1"})
	// One page per sub-chunk and a budget smaller than a single chunk forces
	// the exempt-job path and constant blocking; it must still finish and match.
	pressured := run("pressured.sql", map[string]string{
		"DMDUL_UNLOAD_WORKERS":     "4",
		"DMDUL_UNLOAD_CHUNK_BYTES": "1",
		"DMDUL_UNLOAD_MEM_BYTES":   "1",
	})
	if !bytes.Equal(seq, pressured) {
		t.Fatalf("backpressured output diverged from sequential (len %d vs %d)", len(seq), len(pressured))
	}
}

func TestResolveDataFilePathPrefersDataDirOverControlAbsolute(t *testing.T) {
	dataDir := t.TempDir()
	liveDir := t.TempDir()
	// The offline copy the user placed in data_dir, and a same-named "live"
	// file at the absolute path recorded in dm.ctl.
	if err := os.WriteFile(filepath.Join(dataDir, "TBS.DBF"), []byte("offline"), 0644); err != nil {
		t.Fatal(err)
	}
	liveAbs := filepath.Join(liveDir, "TBS.DBF")
	if err := os.WriteFile(liveAbs, []byte("live"), 0644); err != nil {
		t.Fatal(err)
	}
	// data_dir copy must win even though the absolute path also exists.
	got, ok := resolveDataFilePath(liveAbs, dataDir)
	if !ok || got != filepath.Join(dataDir, "TBS.DBF") {
		t.Fatalf("expected data_dir copy to win, got %q ok=%v", got, ok)
	}
	// When the file is NOT in data_dir, fall back to the recorded absolute path.
	otherAbs := filepath.Join(liveDir, "OTHER.DBF")
	if err := os.WriteFile(otherAbs, []byte("x"), 0644); err != nil {
		t.Fatal(err)
	}
	got, ok = resolveDataFilePath(otherAbs, dataDir)
	if !ok || got != otherAbs {
		t.Fatalf("expected fallback to absolute path, got %q ok=%v", got, ok)
	}
}
