package dm

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

func renderDDL(objects map[uint32]dictionaryObject, users map[uint32]dictionaryObject, roles map[uint32]dictionaryObject, roleGrants []roleGrantDef, tables map[uint32]dictionaryObject, columnsByTable map[uint32][]columnDef, columnsByTableColID map[tableColKey]columnDef, indexObjects map[uint32]dictionaryObject, indexes map[uint32]indexDef, tableStorage map[uint32]indexDef, partitionsByTable map[uint32][]PartitionInfo, partitionKeysByTable map[uint32][]uint16, constraintObjects map[uint32]dictionaryObject, constraints []constraintDef, tableComments map[ownerTableKey]tableComment, columnComments map[ownerTableColumnKey]columnComment, views []DictionaryView, sequences []DictionarySequence, routines []DictionaryRoutine, triggers []DictionaryTrigger, synonyms []DictionarySynonym, tabPrivileges []DictionaryTabPrivilege, systemPrivileges []DictionarySystemPrivilege, matcher ownerMatcher, tableMatcher tableNameMatcher, tablespaces map[uint32]string) string {
	var out strings.Builder
	out.WriteString("-- Generated by dmdul export-ddl. Review before running.\n\n")
	renderUsersAndRoles(&out, users, roles, roleGrants, matcher, tablespaces)
	renderSystemPrivileges(&out, systemPrivileges)
	renderCreateSchemas(&out, objects, users, matcher)
	renderCreateTables(&out, tables, columnsByTable, columnsByTableColID, tableStorage, partitionsByTable, partitionKeysByTable, matcher, tableMatcher, tablespaces)
	renderSequences(&out, sequences)
	renderRoutines(&out, routines)
	renderViews(&out, views)
	renderIndexes(&out, tables, columnsByTableColID, indexObjects, indexes, matcher, tableMatcher, tablespaces)
	renderConstraints(&out, objects, tables, columnsByTableColID, constraintObjects, indexes, constraints, matcher, tableMatcher)
	renderComments(&out, tables, columnsByTable, tableComments, columnComments, matcher, tableMatcher)
	renderTriggers(&out, triggers)
	renderSynonyms(&out, synonyms)
	renderTabPrivileges(&out, tabPrivileges)
	return out.String()
}

// renderCreateSchemas emits CREATE SCHEMA for every non-default schema in
// scope. In DM one user owns one or more schemas; the same-named default schema
// is created automatically by CREATE USER, but additional schemas
// (name != owner) must be recreated explicitly or the CREATE TABLE statements
// that follow would target a missing schema. DM's CREATE SCHEMA absorbs the
// following statements as schema elements until a "/" batch terminator, so each
// one is terminated with "/" (verified on DM8: a bare ";" swallows the next
// CREATE TABLE and the schema is not created).
func renderCreateSchemas(out *strings.Builder, objects map[uint32]dictionaryObject, users map[uint32]dictionaryObject, matcher ownerMatcher) {
	schemas := dictionarySchemasFromObjects(objects, users, matcher)
	var lines []string
	for _, schema := range schemas {
		if strings.EqualFold(schema.Name, schema.Owner) {
			continue // default same-name schema is created by CREATE USER
		}
		lines = append(lines, fmt.Sprintf("CREATE SCHEMA %s AUTHORIZATION %s;\n/", quoteIdent(schema.Name), quoteIdent(schema.Owner)))
	}
	if len(lines) == 0 {
		return
	}
	out.WriteString("-- Schemas\n")
	for _, line := range lines {
		out.WriteString(line)
		out.WriteString("\n\n")
	}
}

func renderUsersAndRoles(out *strings.Builder, users map[uint32]dictionaryObject, roles map[uint32]dictionaryObject, roleGrants []roleGrantDef, matcher ownerMatcher, tablespaces map[uint32]string) {
	userIDs := exportedUserIDs(users, matcher)
	roleIDs := exportedRoleIDsForScope(roles, roleGrants, users, userIDs, matcher)
	if len(userIDs) == 0 && len(roleIDs) == 0 {
		return
	}

	out.WriteString("-- Users and roles\n")
	if len(userIDs) > 0 {
		out.WriteString("-- Password hashes are not exported. Change the placeholder password after import.\n")
		for _, userID := range userIDs {
			user := users[userID]
			out.WriteString(renderCreateUser(user, tablespaces))
			out.WriteByte('\n')
		}
		if len(roleIDs) > 0 {
			out.WriteByte('\n')
		}
	}

	for _, roleID := range roleIDs {
		role := roles[roleID]
		out.WriteString(fmt.Sprintf("CREATE ROLE %s;\n", quoteIdent(role.Name)))
	}

	grantLines := renderRoleGrantLines(roleGrants, users, roles, userIDs, roleIDs)
	if len(grantLines) > 0 {
		if len(roleIDs) > 0 || len(userIDs) > 0 {
			out.WriteByte('\n')
		}
		for _, line := range grantLines {
			out.WriteString(line)
			out.WriteByte('\n')
		}
	}
	out.WriteByte('\n')
}

func renderCreateUser(user dictionaryObject, tablespaces map[uint32]string) string {
	parts := []string{
		"CREATE USER " + quoteIdent(user.Name),
		"IDENTIFIED BY " + passwordLiteral(defaultRecoveredPassword),
	}
	if defaultTS := userDefaultTablespaceName(user, tablespaces); defaultTS != "" {
		parts = append(parts, "DEFAULT TABLESPACE "+quoteStorageName(defaultTS))
	}
	if tempTS := tablespaces[3]; tempTS != "" {
		parts = append(parts, "TEMPORARY TABLESPACE "+quoteStorageName(tempTS))
	}
	return strings.Join(parts, " ") + ";"
}

func renderRoleGrantLines(roleGrants []roleGrantDef, users map[uint32]dictionaryObject, roles map[uint32]dictionaryObject, userIDs []uint32, roleIDs []uint32) []string {
	userSet := idSet(userIDs)
	roleSet := idSet(roleIDs)
	linesByKey := make(map[string]string)
	for _, grant := range roleGrants {
		role, ok := roles[grant.RoleID]
		if !ok {
			continue
		}
		granteeName := ""
		if userSet[grant.GranteeID] {
			granteeName = users[grant.GranteeID].Name
		} else if roleSet[grant.GranteeID] {
			granteeName = roles[grant.GranteeID].Name
		}
		if granteeName == "" {
			continue
		}
		line := fmt.Sprintf("GRANT %s TO %s", quoteIdent(role.Name), quoteIdent(granteeName))
		if grant.AdminOption == "Y" {
			line += " WITH ADMIN OPTION"
		}
		line += ";"
		key := role.Name + "\x00" + granteeName + "\x00" + grant.AdminOption
		linesByKey[key] = line
	}
	keys := make([]string, 0, len(linesByKey))
	for key := range linesByKey {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	lines := make([]string, 0, len(keys))
	for _, key := range keys {
		lines = append(lines, linesByKey[key])
	}
	return lines
}

func renderCreateTables(out *strings.Builder, tables map[uint32]dictionaryObject, columnsByTable map[uint32][]columnDef, columnsByTableColID map[tableColKey]columnDef, tableStorage map[uint32]indexDef, partitionsByTable map[uint32][]PartitionInfo, partitionKeysByTable map[uint32][]uint16, matcher ownerMatcher, tableMatcher tableNameMatcher, tablespaces map[uint32]string) {
	out.WriteString("-- Tables\n")
	tableIDs := sortedTableIDs(tables)
	for _, tableID := range tableIDs {
		table := tables[tableID]
		if !matcher.allowed(table.Owner) || !tableMatcher.allowed(table.Owner, table.Name) || len(columnsByTable[tableID]) == 0 {
			continue
		}
		createKind := "CREATE TABLE"
		if table.isHugeTable() {
			createKind = "CREATE HUGE TABLE"
		} else if table.isTemporaryTable() {
			createKind = "CREATE GLOBAL TEMPORARY TABLE"
		}
		out.WriteString(fmt.Sprintf("%s %s.%s (\n", createKind, quoteIdent(table.Owner), quoteIdent(table.Name)))
		var lines []string
		for _, col := range columnsByTable[tableID] {
			line := fmt.Sprintf("    %s %s", quoteIdent(col.Name), formatColumnType(col.DataType, col.Length, col.Scale))
			if col.Default != "" {
				line += " DEFAULT " + col.Default
			}
			if col.Nullable == "N" {
				line += " NOT NULL"
			}
			lines = append(lines, line)
		}
		out.WriteString(strings.Join(lines, ",\n"))
		out.WriteString("\n)")
		if commitClause := table.temporaryCommitClause(); commitClause != "" {
			out.WriteString("\n")
			out.WriteString(commitClause)
		}
		partitionClause := renderPartitionClause(tableID, partitionsByTable[tableID], partitionKeysByTable[tableID], columnsByTableColID)
		if partitionClause != "" && !table.isTemporaryTable() {
			out.WriteString(partitionClause)
		}
		if table.isHugeTable() {
			groupID := uint32(table.Info2 & 0xFFFF)
			if storage, ok := tableStorage[tableID]; ok && storage.GroupID != 0 {
				groupID = uint32(storage.GroupID)
			}
			out.WriteString(hugeStorageClause(table, groupID, tablespaces))
		} else if storage, ok := tableStorage[tableID]; ok && !table.isTemporaryTable() && partitionClause == "" {
			out.WriteString(storageClause(uint32(storage.GroupID), tablespaces, table.tableStorageOrganization()))
		}
		out.WriteString(";\n\n")
	}
}

func renderViews(out *strings.Builder, views []DictionaryView) {
	if len(views) == 0 {
		return
	}
	out.WriteString("-- Views\n")
	for _, view := range views {
		sql := strings.TrimSpace(view.SQL)
		if sql != "" {
			sql = qualifyRecoveredViewName(sql, view.Owner, view.Name)
		}
		if sql == "" && strings.TrimSpace(view.QuerySQL) != "" {
			sql = fmt.Sprintf("CREATE OR REPLACE VIEW %s.%s AS\n%s",
				quoteIdent(view.Owner), quoteIdent(view.Name), strings.TrimSpace(view.QuerySQL))
		}
		if sql == "" {
			fmt.Fprintf(out, "-- WARNING: view text not recovered for %s.%s\n", quoteIdent(view.Owner), quoteIdent(view.Name))
			continue
		}
		out.WriteString(ensureSQLTerminator(sql))
		out.WriteString("\n\n")
	}
}

var recoveredViewHeaderPattern = regexp.MustCompile(`(?is)^(\s*CREATE\s+(?:OR\s+REPLACE\s+)?(?:FORCE\s+)?VIEW\s+)(?:"(?:[^"]|"")*"|[^\s(]+)`)

func qualifyRecoveredViewName(sql, owner, name string) string {
	match := recoveredViewHeaderPattern.FindStringSubmatchIndex(sql)
	if len(match) < 4 {
		return sql
	}
	qualified := quoteIdent(owner) + "." + quoteIdent(name)
	return sql[:match[3]] + qualified + sql[match[1]:]
}

func renderSequences(out *strings.Builder, sequences []DictionarySequence) {
	if len(sequences) == 0 {
		return
	}
	out.WriteString("-- Sequences\n")
	for _, seq := range sequences {
		sql := strings.TrimSpace(seq.SQL)
		if sql == "" {
			if !seq.HasLastNumber {
				fmt.Fprintf(out, "-- WARNING: current value of %s.%s was not recovered; START WITH uses the persisted initial value\n",
					quoteIdent(seq.Owner), quoteIdent(seq.Name))
			}
			if _, _, exhausted := recoveredSequenceStart(seq); exhausted {
				fmt.Fprintf(out, "-- NOTICE: %s.%s was exhausted; the following NEXTVAL preserves its exhausted state\n",
					quoteIdent(seq.Owner), quoteIdent(seq.Name))
			}
			sql = renderRecoveredSequenceSQL(seq)
		}
		out.WriteString(ensureSQLTerminator(sql))
		out.WriteString("\n\n")
	}
}

func renderRecoveredSequenceSQL(seq DictionarySequence) string {
	increment := seq.IncrementBy
	if increment == 0 {
		increment = 1
	}
	var lines []string
	lines = append(lines, fmt.Sprintf("CREATE SEQUENCE %s.%s", quoteIdent(seq.Owner), quoteIdent(seq.Name)))
	startWith, hasStartWith, exhausted := recoveredSequenceStart(seq)
	if hasStartWith {
		lines = append(lines, fmt.Sprintf("START WITH %d", startWith))
	}
	lines = append(lines, fmt.Sprintf("INCREMENT BY %d", increment))
	if seq.HasMinValue || seq.MinValue != 0 {
		lines = append(lines, fmt.Sprintf("MINVALUE %d", seq.MinValue))
	}
	if seq.HasMaxValue || seq.MaxValue != 0 {
		lines = append(lines, fmt.Sprintf("MAXVALUE %d", seq.MaxValue))
	}
	if strings.EqualFold(seq.CycleFlag, "Y") || strings.EqualFold(seq.CycleFlag, "YES") {
		lines = append(lines, "CYCLE")
	} else {
		lines = append(lines, "NOCYCLE")
	}
	if seq.CacheSize > 0 {
		lines = append(lines, fmt.Sprintf("CACHE %d", seq.CacheSize))
	} else {
		lines = append(lines, "NOCACHE")
	}
	if strings.EqualFold(seq.OrderFlag, "Y") || strings.EqualFold(seq.OrderFlag, "YES") {
		lines = append(lines, "ORDER")
	} else {
		lines = append(lines, "NOORDER")
	}
	sql := strings.Join(lines, "\n")
	if exhausted {
		sql += fmt.Sprintf(";\nSELECT %s.%s.NEXTVAL", quoteIdent(seq.Owner), quoteIdent(seq.Name))
	}
	return sql
}

func recoveredSequenceStart(seq DictionarySequence) (int64, bool, bool) {
	start := seq.StartWith
	hasStart := seq.HasStartWith || seq.StartWith != 0
	if !seq.HasLastNumber {
		return start, hasStart, false
	}
	start = seq.LastNumber
	hasStart = true
	increment := seq.IncrementBy
	if increment == 0 {
		increment = 1
	}
	cycle := strings.EqualFold(seq.CycleFlag, "Y") || strings.EqualFold(seq.CycleFlag, "YES")
	if increment > 0 && (seq.HasMaxValue || seq.MaxValue != 0) && start > seq.MaxValue {
		if cycle && (seq.HasMinValue || seq.MinValue != 0) {
			return seq.MinValue, true, false
		}
		return seq.MaxValue, true, true
	}
	if increment < 0 && (seq.HasMinValue || seq.MinValue != 0) && start < seq.MinValue {
		if cycle && (seq.HasMaxValue || seq.MaxValue != 0) {
			return seq.MaxValue, true, false
		}
		return seq.MinValue, true, true
	}
	return start, hasStart, false
}

func renderRoutines(out *strings.Builder, routines []DictionaryRoutine) {
	if len(routines) == 0 {
		return
	}
	out.WriteString("-- Stored routines\n")
	for _, routine := range routines {
		sql := strings.TrimSpace(routine.SQL)
		if sql == "" {
			fmt.Fprintf(out, "-- WARNING: %s text not recovered for %s.%s\n",
				normalizeRoutineObjectType(routine.ObjectType),
				quoteIdent(routine.Owner),
				quoteIdent(routine.Name))
			continue
		}
		out.WriteString(ensurePLSQLBlockTerminator(sql))
		out.WriteString("\n\n")
	}
}

func renderTriggers(out *strings.Builder, triggers []DictionaryTrigger) {
	if len(triggers) == 0 {
		return
	}
	out.WriteString("-- Triggers\n")
	for _, trigger := range triggers {
		sql := strings.TrimSpace(trigger.SQL)
		if sql == "" {
			fmt.Fprintf(out, "-- WARNING: trigger text not recovered for %s.%s\n", quoteIdent(trigger.Owner), quoteIdent(trigger.Name))
			continue
		}
		out.WriteString(ensurePLSQLBlockTerminator(sql))
		out.WriteString("\n\n")
	}
}

func renderSynonyms(out *strings.Builder, synonyms []DictionarySynonym) {
	if len(synonyms) == 0 {
		return
	}
	out.WriteString("-- Synonyms\n")
	for _, syn := range synonyms {
		if syn.Public || strings.EqualFold(syn.Owner, "PUBLIC") {
			fmt.Fprintf(out, "CREATE OR REPLACE PUBLIC SYNONYM %s FOR %s.%s;\n",
				quoteIdent(syn.Name), quoteIdent(syn.TableOwner), quoteIdent(syn.TableName))
			continue
		}
		fmt.Fprintf(out, "CREATE OR REPLACE SYNONYM %s.%s FOR %s.%s;\n",
			quoteIdent(syn.Owner), quoteIdent(syn.Name), quoteIdent(syn.TableOwner), quoteIdent(syn.TableName))
	}
	out.WriteByte('\n')
}

func renderTabPrivileges(out *strings.Builder, privileges []DictionaryTabPrivilege) {
	if len(privileges) == 0 {
		return
	}
	out.WriteString("-- Object privileges\n")
	for _, priv := range privileges {
		if priv.ColumnID != nil && priv.ColumnName == "" {
			fmt.Fprintf(out, "-- WARNING: column privilege omitted: %s.%s column_id=%d grantee=%s (column name unavailable)\n", quoteIdent(priv.Owner), quoteIdent(priv.ObjectName), *priv.ColumnID, quoteIdent(priv.Grantee))
			continue
		}
		privilege := strings.ToUpper(strings.TrimSpace(priv.Privilege))
		if priv.ColumnName != "" {
			privilege += " (" + quoteIdent(priv.ColumnName) + ")"
		}
		fmt.Fprintf(out, "GRANT %s ON %s.%s TO %s",
			privilege,
			quoteIdent(priv.Owner),
			quoteIdent(priv.ObjectName),
			quoteIdent(priv.Grantee))
		if strings.EqualFold(priv.Grantable, "Y") || strings.EqualFold(priv.Grantable, "YES") {
			out.WriteString(" WITH GRANT OPTION")
		}
		out.WriteString(";\n")
	}
	out.WriteByte('\n')
}
